import {
  Activity,
  Aperture,
  ArrowLeftRight,
  Atom,
  Award,
  BarChart3,
  Binary,
  Bookmark,
  BookOpen,
  Boxes,
  Braces,
  Brain,
  Calculator,
  CircleDot,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  Combine,
  Compass,
  Cpu,
  Crosshair,
  Dna,
  Eye,
  FileText,
  Filter,
  Flag,
  Flame,
  FlaskConical,
  Focus,
  Footprints,
  Gauge,
  GitBranch,
  GitFork,
  GraduationCap,
  Grid3x3,
  Hand,
  Hash,
  Headphones,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  Hexagon,
  Highlighter,
  Hourglass,
  Info,
  KeyRound,
  Layers,
  LayoutGrid,
  Library,
  Lightbulb,
  LineChart,
  Link2,
  ListChecks,
  Map,
  Medal,
  MessageSquare,
  MessageSquareText,
  MessagesSquare,
  Microscope,
  Milestone,
  Network,
  Notebook,
  NotebookPen,
  Orbit,
  Pencil,
  PenLine,
  Percent,
  Pi,
  PieChart,
  PlayCircle,
  Pointer,
  Puzzle,
  Quote,
  Radar,
  RefreshCw,
  Repeat,
  Rocket,
  Route,
  Ruler,
  Scale,
  Scan,
  ScanSearch,
  School,
  Search,
  Shapes,
  ShieldCheck,
  Sigma,
  Sparkles,
  Split,
  Square,
  Star,
  Stethoscope,
  Table2,
  Target,
  Timer,
  Triangle,
  Trophy,
  UserCheck,
  UserRoundCheck,
  Users,
  Video,
  Wand2,
  Waypoints,
  Workflow,
  Zap,
  Infinity as InfinityIcon,
  type LucideIcon,
} from "lucide-react";

const LEARNING_MODULE_ICONS: Record<string, LucideIcon> = {
  "book-open": BookOpen,
  lightbulb: Lightbulb,
  target: Target,
  brain: Brain,
  calculator: Calculator,
  compass: Compass,
  sparkles: Sparkles,
  "file-text": FileText,
  "graduation-cap": GraduationCap,
  school: School,
  library: Library,
  pencil: Pencil,
  "pen-line": PenLine,
  highlighter: Highlighter,
  notebook: Notebook,
  "notebook-pen": NotebookPen,
  "clipboard-list": ClipboardList,
  "clipboard-check": ClipboardCheck,
  "list-checks": ListChecks,
  bookmark: Bookmark,
  star: Star,
  "clock-3": Clock3,
  timer: Timer,
  hourglass: Hourglass,
  gauge: Gauge,
  zap: Zap,
  flame: Flame,
  rocket: Rocket,
  layers: Layers,
  "layout-grid": LayoutGrid,
  boxes: Boxes,
  shapes: Shapes,
  puzzle: Puzzle,
  "git-branch": GitBranch,
  "git-fork": GitFork,
  workflow: Workflow,
  network: Network,
  split: Split,
  combine: Combine,
  repeat: Repeat,
  "refresh-cw": RefreshCw,
  infinity: InfinityIcon,
  "link-2": Link2,
  filter: Filter,
  waypoints: Waypoints,
  route: Route,
  map: Map,
  milestone: Milestone,
  flag: Flag,
  focus: Focus,
  crosshair: Crosshair,
  aperture: Aperture,
  radar: Radar,
  orbit: Orbit,
  "arrow-left-right": ArrowLeftRight,
  eye: Eye,
  search: Search,
  scan: Scan,
  "scan-search": ScanSearch,
  quote: Quote,
  "message-square": MessageSquare,
  "message-square-text": MessageSquareText,
  "messages-square": MessagesSquare,
  info: Info,
  "help-circle": HelpCircle,
  percent: Percent,
  sigma: Sigma,
  pi: Pi,
  binary: Binary,
  hash: Hash,
  braces: Braces,
  ruler: Ruler,
  "table-2": Table2,
  "grid-3x3": Grid3x3,
  "bar-chart-3": BarChart3,
  "line-chart": LineChart,
  "pie-chart": PieChart,
  triangle: Triangle,
  "circle-dot": CircleDot,
  square: Square,
  hexagon: Hexagon,
  scale: Scale,
  users: Users,
  "user-check": UserCheck,
  "user-round-check": UserRoundCheck,
  "heart-handshake": HeartHandshake,
  "shield-check": ShieldCheck,
  hand: Hand,
  pointer: Pointer,
  footprints: Footprints,
  trophy: Trophy,
  award: Award,
  medal: Medal,
  "key-round": KeyRound,
  atom: Atom,
  dna: Dna,
  microscope: Microscope,
  "flask-conical": FlaskConical,
  stethoscope: Stethoscope,
  activity: Activity,
  "heart-pulse": HeartPulse,
  cpu: Cpu,
  "play-circle": PlayCircle,
  video: Video,
  headphones: Headphones,
  "wand-2": Wand2,
};

export function getLearningModuleIcon(iconKey: string | null): LucideIcon {
  return LEARNING_MODULE_ICONS[iconKey ?? ""] ?? BookOpen;
}
