begin;
select plan(26);
insert into auth.users(id) values ('ef000000-0000-4000-8000-000000000001'),('ef000000-0000-4000-8000-000000000002');
insert into public.staff(id,user_id,first_name,last_name,role,status) values
('ef000000-0000-4000-8000-000000000011','ef000000-0000-4000-8000-000000000001','Alice','Autosave','ADMINSTAFF','ACTIVE'),
('ef000000-0000-4000-8000-000000000012','ef000000-0000-4000-8000-000000000002','Bob','Autosave','ADMINSTAFF','ACTIVE');
select set_config('request.jwt.claims','{"sub":"ef000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
create temporary table work as select public.admin_work_item_change('task',null,null,'autosave-create','{"title":"Existing","description":"Important"}') as body;
create temporary table target as select (body#>>'{record,id}')::uuid as id from work;
select is(public.admin_work_item_edit('task',(select id from target),'read')#>>'{record,description}','Important','viewing loads saved description');
select lives_ok(format('select public.admin_work_item_patch(''task'',%L,''{}'',''{}'',''empty'')',(select id from target)),'an empty patch is a no-op');
select is(public.admin_work_item_read('task',(select id from target))#>>'{record,admin_revision}','1','empty patch does not write or create a version');
select is(public.admin_work_item_patch('task',(select id from target),'{"assigned_to":"ef000000-0000-4000-8000-000000000011"}','{"assigned_to":null}','assignee')#>>'{record,description}','Important','assignee patch never touches description');
select set_config('request.jwt.claims','{"sub":"ef000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is(public.admin_work_item_patch('task',(select id from target),'{"description":"Bob writing"}','{"description":"Important"}','bob-description')->'conflicts','[]'::jsonb,'another user saves description from an older record snapshot');
select is(public.admin_work_item_read('task',(select id from target))#>>'{record,assigned_to}','ef000000-0000-4000-8000-000000000011','description patch preserves assignee');
select set_config('request.jwt.claims','{"sub":"ef000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
create temporary table conflict as select public.admin_work_item_patch('task',(select id from target),'{"description":"Alice writing","priority":2}','{"description":"Important","priority":0}','alice-conflict') as body;
select is((select body->'conflicts' from conflict),'["description"]'::jsonb,'same-field stale save reports a conflict');
select is((select body#>>'{record,description}' from conflict),'Bob writing','conflict returns latest saved text');
select is(public.admin_work_item_read('task',(select id from target))#>>'{record,description}','Bob writing','conflict never overwrites someone else’s work');
select is(public.admin_work_item_read('task',(select id from target))#>>'{record,priority}','0','conflicting multi-field patch is atomic');
select is(public.admin_work_item_patch('task',(select id from target),'{"priority":2}','{"priority":0}','priority')->'conflicts','[]'::jsonb,'unrelated field can still save while description conflicts');
select is(public.admin_work_item_patch('task',(select id from target),'{"description":"Alice writing"}','{"description":"Bob writing"}','resolved')->'conflicts','[]'::jsonb,'reviewed conflict can explicitly replace the latest value');
select is(public.admin_work_item_patch('task',(select id from target),'{"description":"Alice writing"}','{"description":"Bob writing"}','resolved')#>>'{record,admin_revision}','5','same-key retry does not write twice');
select throws_ok(format('select public.admin_work_item_patch(''task'',%L,''{"description":"Different"}'',''{"description":"Bob writing"}'',''resolved'')',(select id from target)),'22023','Autosave request key reused','different input cannot reuse a receipt');
select is(public.admin_work_item_patch('task',(select id from target),'{"description":null}','{"description":"Alice writing"}','clear')#>'{record,description}','null'::jsonb,'deliberate clearing saves with its expected value');
select throws_ok(format('select public.admin_work_item_patch(''task'',%L,''{"description":null}'',''{}'',''missing-expected'')',(select id from target)),'22023',null,'missing expectation cannot clear a description');
select throws_ok(format('select public.admin_work_item_patch(''task'',%L,''{"created_by":null}'',''{"created_by":null}'',''protected-field'')',(select id from target)),'22023',null,'protected properties are not writable');
select throws_ok(format('update public.tasks set description=null where id=%L',(select id from target)),'55P03',null,'direct writes still cannot bypass the guarded save path');
select is(public.admin_work_item_patch('task',(select id from target),'{"priority":2}','{"priority":0}','same-value')->'conflicts','[]'::jsonb,'already matching values do not need conflict resolution');
create temporary table project as select public.admin_work_item_change('project',null,null,'autosave-project','{"name":"Project","description":"Project work"}') as body;
select is(public.admin_work_item_patch('project',(select (body#>>'{record,id}')::uuid from project),'{"member_ids":["ef000000-0000-4000-8000-000000000012"]}','{"member_ids":[]}','members')#>>'{record,description}','Project work','project member changes preserve description');
select is(public.admin_work_item_patch('project',(select (body#>>'{record,id}')::uuid from project),'{"member_ids":[]}','{"member_ids":[]}','members-stale')->'conflicts','["member_ids"]'::jsonb,'project members participate in field conflict checks');
create temporary table issue as select public.admin_work_item_change('issue',null,null,'autosave-issue','{"name":"Issue","description":"Issue work"}') as body;
select is(public.admin_work_item_patch('issue',(select (body#>>'{record,id}')::uuid from issue),'{"name":"Renamed"}','{"name":"Issue"}','issue-name')#>>'{record,description}','Issue work','issue name changes preserve description');
create temporary table document as select public.admin_work_item_change('document',null,null,'autosave-document','{"title":"Document","content":"Document work"}') as body;
select is(public.admin_work_item_patch('document',(select (body#>>'{record,id}')::uuid from document),'{"title":"Renamed"}','{"title":"Document"}','document-title')#>>'{record,content}','Document work','document title changes preserve content');
select is(public.admin_work_item_patch('document',(select (body#>>'{record,id}')::uuid from document),'{"content":"New writing"}','{"content":"Document work"}','document-content')->'conflicts','[]'::jsonb,'document content saves independently of title');
select is(public.admin_work_item_patch('document',(select (body#>>'{record,id}')::uuid from document),'{"content":"Stale writing"}','{"content":"Document work"}','document-stale')->'conflicts','["content"]'::jsonb,'document content rejects stale saves');
grant select on target to anon;
reset role;
select set_config('request.jwt.claims','{"role":"anon"}',true);
set local role anon;
select throws_ok(format('select public.admin_work_item_patch(''task'',%L,''{}'',''{}'',''anonymous'')',(select id from target)),'42501',null,'anonymous callers cannot autosave');
select * from finish();
rollback;
