// Generated by @altitutor/email. Edit packages/email/src instead.

// src/render-email.ts
var EMAIL_SENDERS = {
  altitutor: {
    from: "Altitutor <admin@altitutor.com>",
    replyTo: "admin@altitutor.com"
  },
  "ucat-product": {
    from: "Altitutor UCAT <admin@altitutor.com>",
    replyTo: "admin@altitutor.com"
  },
  founder: {
    from: "Matt at Altitutor <matt@altitutor.com>",
    replyTo: "matt@altitutor.com"
  }
};
var EMAIL_BRANDS = {
  altitutor: {
    name: "Altitutor",
    subtitle: null
  },
  ucat: {
    name: "Altitutor UCAT",
    subtitle: "UCAT preparation from Altitutor"
  }
};
function escapeEmailHtml(value) {
  return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
}
function renderEmailButton(href, label) {
  return `<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:26px 0">
    <tr>
      <td class="email-button-cell" bgcolor="#0a2941" style="border-radius:10px;background-color:#0a2941">
        <a class="email-button" href="${escapeEmailHtml(href)}" style="display:inline-block;min-width:176px;padding:14px 22px;border-radius:10px;color:#ffffff;font-size:15px;font-weight:700;line-height:1.4;text-align:center;text-decoration:none">${escapeEmailHtml(label)}</a>
      </td>
    </tr>
  </table>`;
}
function renderEmailPanel(bodyHtml, tone = "blue") {
  const background = tone === "cream" ? "#f7f2e8" : "#eaf1f3";
  const border = tone === "cream" ? "#e8dcc8" : "#d1e0e5";
  return `<table class="email-panel" role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" bgcolor="${background}" style="margin:22px 0;background-color:${background};border:1px solid ${border};border-radius:12px">
    <tr>
      <td class="email-panel-copy" style="padding:18px 20px;color:#223b4b;font-size:14px;line-height:1.65">${bodyHtml}</td>
    </tr>
  </table>`;
}
function renderEmail(input) {
  const brand = EMAIL_BRANDS[input.brand];
  const sender = EMAIL_SENDERS[input.sender ?? (input.brand === "ucat" ? "ucat-product" : "altitutor")];
  const year = input.year ?? (/* @__PURE__ */ new Date()).getUTCFullYear();
  const subtitle = brand.subtitle ? `<p class="email-brand-subtitle" style="margin:6px 0 0;color:#b9d1d9;font-size:13px;line-height:1.5">${escapeEmailHtml(brand.subtitle)}</p>` : "";
  const footerHtml = input.footerHtml ?? `<p style="margin:0;color:#52606a;font-size:12px;line-height:1.6">Need help? Reply to this email or contact <a class="email-link" href="mailto:${sender.replyTo}" style="color:#0a2941">${sender.replyTo}</a>.</p>`;
  const brandFooterHtml = input.brand === "ucat" ? `<p class="email-accent" style="margin:0 0 3px;color:#0a2941;font-size:13px;font-weight:700;line-height:1.5">Altitutor UCAT</p>
            <p style="margin:0 0 10px;color:#52606a;font-size:12px;line-height:1.5">A not-for-profit initiative by Altitutor.</p>` : `<p class="email-accent" style="margin:0 0 8px;color:#0a2941;font-size:13px;font-weight:700;line-height:1.5">Altitutor</p>`;
  return {
    subject: input.subject,
    previewText: input.previewText,
    text: `${input.heading}

${input.bodyText}`,
    from: sender.from,
    replyTo: sender.replyTo,
    html: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="color-scheme" content="light dark">
    <meta name="supported-color-schemes" content="light dark">
    <title>${escapeEmailHtml(input.heading)}</title>
    <style>
      :root { color-scheme: light dark; supported-color-schemes: light dark; }
      a { color: #0a2941; }
      @media only screen and (max-width: 620px) {
        .email-page-pad { padding: 18px 10px !important; }
        .email-header, .email-content, .email-footer { padding-left: 22px !important; padding-right: 22px !important; }
        .email-heading { font-size: 23px !important; }
        .email-button { display: block !important; min-width: 0 !important; }
      }
      @media (prefers-color-scheme: dark) {
        body, .email-page { background-color: #171717 !important; }
        .email-card, .email-content, .email-header { background-color: #1f1f1f !important; }
        .email-card, .email-header { border-color: #2b2b2b !important; }
        a, .email-brand, .email-link, .email-accent,
        .email-panel-copy .email-accent { color: #92b5c3 !important; }
        .email-brand-subtitle, .email-muted { color: #b3b3b3 !important; }
        .email-heading, .email-strong { color: #ffffff !important; }
        .email-copy, .email-copy p, .email-copy li { color: #f5f5f5 !important; }
        .email-panel { background-color: #262626 !important; border-color: #2b2b2b !important; }
        .email-panel-copy, .email-panel-copy p, .email-panel-copy td { color: #f5f5f5 !important; }
        .email-module-surface { background-color: #2b2b2b !important; border-color: #2b2b2b !important; }
        .email-footer { background-color: #262626 !important; border-color: #2b2b2b !important; }
        .email-footer p { color: #b3b3b3 !important; }
        .email-footer a { color: #92b5c3 !important; }
        .email-button-cell { background-color: #92b5c3 !important; }
        .email-button { color: #1c1c1c !important; }
        .email-accent-fill { background-color: #92b5c3 !important; color:#1c1c1c !important; }
      }
      [data-ogsc] body, [data-ogsc] .email-page { background-color: #171717 !important; }
      [data-ogsc] .email-card, [data-ogsc] .email-content, [data-ogsc] .email-header { background-color: #1f1f1f !important; }
      [data-ogsc] .email-card, [data-ogsc] .email-header { border-color: #2b2b2b !important; }
      [data-ogsc] a, [data-ogsc] .email-brand, [data-ogsc] .email-link,
      [data-ogsc] .email-accent, [data-ogsc] .email-panel-copy .email-accent { color: #92b5c3 !important; }
      [data-ogsc] .email-brand-subtitle, [data-ogsc] .email-muted { color: #b3b3b3 !important; }
      [data-ogsc] .email-heading, [data-ogsc] .email-strong { color: #ffffff !important; }
      [data-ogsc] .email-copy, [data-ogsc] .email-copy p, [data-ogsc] .email-copy li { color: #f5f5f5 !important; }
      [data-ogsc] .email-panel { background-color: #262626 !important; border-color: #2b2b2b !important; }
      [data-ogsc] .email-panel-copy, [data-ogsc] .email-panel-copy p, [data-ogsc] .email-panel-copy td { color: #f5f5f5 !important; }
      [data-ogsc] .email-module-surface { background-color: #2b2b2b !important; border-color: #2b2b2b !important; }
      [data-ogsc] .email-footer { background-color: #262626 !important; border-color: #2b2b2b !important; }
      [data-ogsc] .email-footer p { color: #b3b3b3 !important; }
      [data-ogsc] .email-footer a { color: #92b5c3 !important; }
      [data-ogsc] .email-button-cell { background-color: #92b5c3 !important; }
      [data-ogsc] .email-button { color: #1c1c1c !important; }
      [data-ogsb] .email-accent-fill { background-color: #92b5c3 !important; }
      [data-ogsc] .email-accent-fill { color: #1c1c1c !important; }
    </style>
    <!--[if mso]><style type="text/css">body, table, td, a { font-family: Arial, sans-serif !important; }</style><![endif]-->
  </head>
  <body style="margin:0;padding:0;background-color:#f2f0e9;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1a1a1a">
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent">${escapeEmailHtml(input.previewText)}</div>
    <table class="email-page" role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" bgcolor="#f2f0e9" style="width:100%;background-color:#f2f0e9">
      <tr><td class="email-page-pad" align="center" style="padding:32px 16px">
        <table class="email-card" role="presentation" cellspacing="0" cellpadding="0" border="0" width="600" bgcolor="#ffffff" style="width:100%;max-width:600px;background-color:#ffffff;border:1px solid #dce5e8;border-radius:16px;overflow:hidden">
          <tr><td class="email-header" bgcolor="#0a2941" style="padding:30px 36px;background-color:#0a2941;border-bottom:1px solid #0a2941">
            <p class="email-brand" style="margin:0;color:#f2f0e9;font-size:24px;font-weight:700;letter-spacing:-0.4px">${escapeEmailHtml(brand.name)}</p>${subtitle ? `
            ${subtitle}` : ""}
          </td></tr>
          <tr><td class="email-content email-copy" bgcolor="#ffffff" style="padding:36px;background-color:#ffffff;color:#394650">
            <h1 class="email-heading" style="margin:0 0 18px;color:#0a2941;font-size:26px;font-weight:700;line-height:1.25">${escapeEmailHtml(input.heading)}</h1>
            ${input.bodyHtml}
          </td></tr>
          <tr><td class="email-footer" bgcolor="#eaf1f3" style="padding:24px 36px;background-color:#eaf1f3;border-top:1px solid #dce5e8">
            ${brandFooterHtml}
            ${footerHtml}${input.marketingFooterHtml ? `
            ${input.marketingFooterHtml}` : ""}
            <p style="margin:12px 0 0;color:#73808a;font-size:11px;line-height:1.5">&copy; ${year} Altitutor.</p>
          </td></tr>
        </table>
      </td></tr>
    </table>
  </body>
</html>`
  };
}

// src/canonical-emails.ts
var paragraphStyle = "margin:0 0 18px;color:#394650;font-size:15px;line-height:1.7";
var mutedStyle = "margin:0;color:#68757e;font-size:13px;line-height:1.6";
function textWithBreaks(value) {
  return escapeEmailHtml(value).replaceAll("\n", "<br />");
}
function actionFallback(url) {
  const safeUrl = escapeEmailHtml(url);
  return `<p class="email-muted" style="${mutedStyle}">If the button does not work, copy this link into your browser:<br /><a class="email-link" href="${safeUrl}" style="color:#0a2941;word-break:break-all">${safeUrl}</a></p>`;
}
function buildInvitationEmail(input) {
  const heading = "Create your Altitutor account";
  const expiry = input.expiresIn ?? "1 hour";
  const introductionHtml = input.staffIntroduction ? `<p class="email-copy" style="${paragraphStyle}">${textWithBreaks(input.staffIntroduction)}</p>` : "";
  const introductionText = input.staffIntroduction ? `${input.staffIntroduction}

` : "";
  const bodyText = `Hello ${input.recipientName},

${introductionText}You\u2019ve been invited to create your Altitutor account.

Create account: ${input.inviteUrl}

This invitation link expires in ${expiry}. If you did not expect this invitation, you can safely ignore this email.`;
  return renderEmail({
    brand: "altitutor",
    subject: "You\u2019ve been invited to Altitutor",
    previewText: "Create your Altitutor account using your secure invitation.",
    heading,
    bodyText,
    bodyHtml: `
      <p class="email-copy" style="${paragraphStyle}">Hello ${escapeEmailHtml(input.recipientName)},</p>
      ${introductionHtml}
      <p class="email-copy" style="${paragraphStyle}">You\u2019ve been invited to create your Altitutor account. Use the secure invitation below to get started.</p>
      ${renderEmailButton(input.inviteUrl, "Create account")}
      ${actionFallback(input.inviteUrl)}
      <p class="email-muted" style="margin:18px 0 0;color:#68757e;font-size:13px;line-height:1.6">This invitation link expires in ${escapeEmailHtml(expiry)}. If you did not expect this invitation, you can safely ignore this email.</p>
    `
  });
}
function buildRegistrationEmail(input) {
  const heading = `Complete registration for ${input.studentName}`;
  const introductionHtml = input.staffIntroduction ? `<p class="email-copy" style="${paragraphStyle}">${textWithBreaks(input.staffIntroduction)}</p>` : "";
  const introductionText = input.staffIntroduction ? `${input.staffIntroduction}

` : "";
  const bodyText = `Hello ${input.recipientName},

${introductionText}Please complete ${input.studentName}\u2019s student registration.

Complete registration: ${input.registrationUrl}

If you did not expect this email, you can safely ignore it.`;
  return renderEmail({
    brand: "altitutor",
    subject: `Complete registration for ${input.studentName} \u2014 Altitutor`,
    previewText: `Complete ${input.studentName}\u2019s Altitutor registration.`,
    heading,
    bodyText,
    bodyHtml: `
      <p class="email-copy" style="${paragraphStyle}">Hello ${escapeEmailHtml(input.recipientName)},</p>
      ${introductionHtml}
      <p class="email-copy" style="${paragraphStyle}">Please complete ${escapeEmailHtml(input.studentName)}\u2019s student registration using the secure link below.</p>
      ${renderEmailButton(input.registrationUrl, "Complete registration")}
      ${actionFallback(input.registrationUrl)}
      <p class="email-muted" style="margin:18px 0 0;color:#68757e;font-size:13px;line-height:1.6">If you did not expect this email, you can safely ignore it.</p>
    `
  });
}
function buildBookingConfirmationEmail(input) {
  const heading = "Your booking confirmation";
  const when = input.sessionDate && input.sessionTime ? ` for ${input.sessionDate} at ${input.sessionTime}` : "";
  const introductionHtml = input.staffIntroduction ? `<p class="email-copy" style="${paragraphStyle}">${textWithBreaks(input.staffIntroduction)}</p>` : "";
  const introductionText = input.staffIntroduction ? `${input.staffIntroduction}

` : "";
  const bodyText = `Hello ${input.recipientName},

${introductionText}Your booking confirmation${when} is ready.

View booking confirmation: ${input.bookingUrl}`;
  return renderEmail({
    brand: "altitutor",
    subject: `Booking confirmation for ${input.studentName} \u2014 Altitutor`,
    previewText: `View ${input.studentName}\u2019s Altitutor booking confirmation.`,
    heading,
    bodyText,
    bodyHtml: `
      <p class="email-copy" style="${paragraphStyle}">Hello ${escapeEmailHtml(input.recipientName)},</p>
      ${introductionHtml}
      <p class="email-copy" style="${paragraphStyle}">Your booking confirmation${escapeEmailHtml(when)} is ready.</p>
      ${renderEmailButton(input.bookingUrl, "View booking confirmation")}
      ${actionFallback(input.bookingUrl)}
    `
  });
}
function buildBookingChangedEmail(input) {
  const heading = "Your session has changed";
  const bodyText = `Hello ${input.recipientName},

Your booking has been updated to ${input.sessionDate} at ${input.sessionTime}.

View updated booking: ${input.bookingUrl}`;
  return renderEmail({
    brand: "altitutor",
    subject: "Your Altitutor session has changed",
    previewText: `Your session is now ${input.sessionDate} at ${input.sessionTime}.`,
    heading,
    bodyText,
    bodyHtml: `
      <p class="email-copy" style="${paragraphStyle}">Hello ${escapeEmailHtml(input.recipientName)},</p>
      <p class="email-copy" style="${paragraphStyle}">Your booking has been updated to <strong class="email-strong" style="color:#0a2941">${escapeEmailHtml(input.sessionDate)}</strong> at <strong class="email-strong" style="color:#0a2941">${escapeEmailHtml(input.sessionTime)}</strong>.</p>
      ${renderEmailButton(input.bookingUrl, "View updated booking")}
      ${actionFallback(input.bookingUrl)}
    `
  });
}
function buildBookingCancelledEmail(input) {
  const heading = "Your session has been cancelled";
  const bodyText = `Hello ${input.recipientName},

Your booking on ${input.sessionDate} at ${input.sessionTime} has been cancelled.

If this was a mistake or you would like to book again, reply to this email.`;
  return renderEmail({
    brand: "altitutor",
    subject: "Your Altitutor session has been cancelled",
    previewText: `Your session on ${input.sessionDate} has been cancelled.`,
    heading,
    bodyText,
    bodyHtml: `
      <p class="email-copy" style="${paragraphStyle}">Hello ${escapeEmailHtml(input.recipientName)},</p>
      <p class="email-copy" style="${paragraphStyle}">Your booking on <strong class="email-strong" style="color:#0a2941">${escapeEmailHtml(input.sessionDate)}</strong> at <strong class="email-strong" style="color:#0a2941">${escapeEmailHtml(input.sessionTime)}</strong> has been cancelled.</p>
      <p class="email-copy" style="${paragraphStyle}">If this was a mistake or you would like to book again, reply to this email.</p>
    `
  });
}
function buildInvoiceNotificationEmail(input) {
  const heading = `Invoice ${input.invoiceNumber} is ready`;
  const hostedAction = input.hostedInvoiceUrl ? renderEmailButton(input.hostedInvoiceUrl, "View and pay invoice") + actionFallback(input.hostedInvoiceUrl) : "";
  const pdfAction = input.invoicePdfUrl ? `<p style="margin:18px 0 0;color:#394650;font-size:14px;line-height:1.6"><a class="email-link" href="${escapeEmailHtml(input.invoicePdfUrl)}" style="color:#0a2941;font-weight:600">Download invoice PDF</a></p>` : "";
  const textActions = [
    input.hostedInvoiceUrl ? `Hosted invoice: ${input.hostedInvoiceUrl}` : null,
    input.invoicePdfUrl ? `Invoice PDF: ${input.invoicePdfUrl}` : null
  ].filter((value) => value !== null).join("\n");
  const bodyText = `Invoice date: ${input.invoiceDate}
Due date: ${input.dueDate}
Amount: ${input.amount}${textActions ? `

${textActions}` : ""}`;
  return renderEmail({
    brand: "altitutor",
    subject: `Invoice ${input.invoiceNumber} is ready \u2014 Altitutor`,
    previewText: `Invoice ${input.invoiceNumber} for ${input.amount} is ready.`,
    heading,
    bodyText,
    bodyHtml: `
      <p class="email-copy" style="${paragraphStyle}">Your Altitutor invoice is ready. Stripe securely hosts the invoice and payment page.</p>
      <table class="email-panel" role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" bgcolor="#eaf1f3" style="margin:22px 0;background-color:#eaf1f3;border:1px solid #d1e0e5;border-radius:12px">
        <tr><td style="padding:12px 20px;border-bottom:1px solid #d1e0e5;color:#52606a;font-size:14px">Invoice date</td><td align="right" style="padding:12px 20px;border-bottom:1px solid #d1e0e5;color:#223b4b;font-size:14px;font-weight:600">${escapeEmailHtml(input.invoiceDate)}</td></tr>
        <tr><td style="padding:12px 20px;border-bottom:1px solid #d1e0e5;color:#52606a;font-size:14px">Due date</td><td align="right" style="padding:12px 20px;border-bottom:1px solid #d1e0e5;color:#223b4b;font-size:14px;font-weight:600">${escapeEmailHtml(input.dueDate)}</td></tr>
        <tr><td style="padding:14px 20px;color:#52606a;font-size:14px">Amount</td><td align="right" style="padding:14px 20px;color:#0a2941;font-size:18px;font-weight:700">${escapeEmailHtml(input.amount)}</td></tr>
      </table>
      ${hostedAction}
      ${pdfAction}
    `
  });
}
function buildContactRequestEmail(input) {
  const diagnostics = JSON.stringify(input.diagnostics ?? {}, null, 2);
  const replyTo = input.contact?.email || input.user?.email || EMAIL_SENDERS.altitutor.replyTo;
  const userName = input.user?.name ?? "Unknown";
  const userEmail = input.user?.email ?? "no email";
  const userId = input.user?.id ?? "unknown";
  const contactPhone = input.contact?.phone ?? "not provided";
  const text = `Contact request

App: ${input.appName}
User: ${userName} (${userEmail})
User ID: ${userId}
Reply email: ${replyTo}
Phone: ${contactPhone}

Message
${input.message}

Diagnostics
${diagnostics}`;
  return {
    subject: `[${input.appName}] Contact request`,
    previewText: `Contact request from ${userName}`,
    from: EMAIL_SENDERS.altitutor.from,
    replyTo,
    text,
    html: `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Contact request</title></head><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1a1a1a"><h2>Contact request</h2><p><strong>App:</strong> ${escapeEmailHtml(input.appName)}</p><p><strong>User:</strong> ${escapeEmailHtml(userName)} (${escapeEmailHtml(userEmail)})</p><p><strong>User ID:</strong> ${escapeEmailHtml(userId)}</p><p><strong>Reply email:</strong> ${escapeEmailHtml(replyTo)}</p><p><strong>Phone:</strong> ${escapeEmailHtml(contactPhone)}</p><h3>Message</h3><p>${textWithBreaks(input.message)}</p><h3>Diagnostics</h3><pre>${escapeEmailHtml(diagnostics)}</pre></body></html>`
  };
}

// src/auth-emails.ts
var copyStyle = "margin:0 0 18px;color:#394650;font-size:15px;line-height:1.7";
var mutedStyle2 = "margin:0;color:#68757e;font-size:13px;line-height:1.6";
function codePanel(label, token) {
  return `<table class="email-panel" role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" bgcolor="#eaf1f3" style="margin:28px 0;background-color:#eaf1f3;border:1px solid #d1e0e5;border-radius:12px"><tr><td align="center" style="padding:22px 18px">
    <p class="email-muted" style="margin:0 0 8px;color:#52606a;font-size:11px;font-weight:700;letter-spacing:0.14em;text-transform:uppercase">${escapeEmailHtml(label)}</p>
    <p class="email-heading" style="margin:0;color:#0a2941;font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;font-size:32px;font-weight:800;letter-spacing:0.28em">${token}</p>
  </td></tr></table>`;
}
function fallbackLink(url) {
  const safeUrl = escapeEmailHtml(url);
  return `<p class="email-muted" style="${mutedStyle2}">If the button does not work, copy this link into your browser:<br /><a class="email-link" href="${safeUrl}" style="color:#0a2941;word-break:break-all">${safeUrl}</a></p>`;
}
function identityEmail(input) {
  return renderEmail({
    brand: "altitutor",
    ...input
  });
}
function buildAuthEmails(input = {}) {
  const year = input.year ?? (/* @__PURE__ */ new Date()).getUTCFullYear();
  const token = "{{ .Token }}";
  const confirmationUrl = "{{ .ConfirmationURL }}";
  const recoveryUrl = "{{ .RedirectTo }}?token_hash={{ .TokenHash }}&type=recovery";
  return {
    confirmation: identityEmail({
      year,
      subject: "Your Altitutor signup code",
      previewText: "Use this code to finish creating your Altitutor account.",
      heading: "Confirm your email",
      bodyText: `Enter this code on the signup page to confirm your email:

${token}

This code expires in 1 hour.`,
      bodyHtml: `<p class="email-copy" style="${copyStyle}">Enter this code on the signup page to confirm your email and finish creating your Altitutor account.</p>${codePanel("Your signup code", token)}<p class="email-muted" style="${mutedStyle2}">This code expires in 1 hour. If you did not request it, you can safely ignore this email.</p>`
    }),
    invite: identityEmail({
      year,
      subject: "You have been invited to Altitutor",
      previewText: "Accept your invitation to create an Altitutor account.",
      heading: "You have been invited",
      bodyText: `You have been invited to create an Altitutor account.

Accept invitation: ${confirmationUrl}`,
      bodyHtml: `<p class="email-copy" style="${copyStyle}">You have been invited to create an Altitutor account. Accept the invitation to get started.</p>${renderEmailButton(confirmationUrl, "Accept invitation")}<p class="email-muted" style="margin:0 0 12px;color:#68757e;font-size:13px;line-height:1.6">If you did not expect this invitation, you can safely ignore this email.</p>${fallbackLink(confirmationUrl)}`
    }),
    magic_link: identityEmail({
      year,
      subject: "Your Altitutor sign-in code",
      previewText: "Use this code to sign in to Altitutor.",
      heading: "Sign in to Altitutor",
      bodyText: `Enter this code on the sign-in page:

${token}

This code expires in 1 hour.`,
      bodyHtml: `<p class="email-copy" style="${copyStyle}">Enter this code on the sign-in page to continue.</p>${codePanel("Your sign-in code", token)}<p class="email-muted" style="${mutedStyle2}">This code expires in 1 hour. If you did not request it, you can safely ignore this email.</p>`
    }),
    recovery: identityEmail({
      year,
      subject: "Reset your Altitutor password",
      previewText: "Choose a new password for your Altitutor account.",
      heading: "Reset your password",
      bodyText: `We received a request to reset your Altitutor password.

Reset password: ${recoveryUrl}

This link expires in 1 hour.`,
      bodyHtml: `<p class="email-copy" style="${copyStyle}">We received a request to reset the password for your Altitutor account. Choose a new password using the button below.</p>${renderEmailButton(recoveryUrl, "Reset password")}<p class="email-muted" style="margin:0 0 12px;color:#68757e;font-size:13px;line-height:1.6">This link expires in 1 hour. If you did not request a password reset, you can safely ignore this email and your password will remain unchanged.</p>${fallbackLink(recoveryUrl)}`
    }),
    email_change: identityEmail({
      year,
      subject: "Confirm your Altitutor email change",
      previewText: "Confirm the new email address for your Altitutor account.",
      heading: "Confirm your new email",
      bodyText: `You asked to change your Altitutor email address to {{ .NewEmail }}.

Confirm new email: ${confirmationUrl}`,
      bodyHtml: `<p class="email-copy" style="${copyStyle}">You asked to change the email address on your Altitutor account to <strong class="email-strong" style="color:#0a2941">{{ .NewEmail }}</strong>.</p>${renderEmailButton(confirmationUrl, "Confirm new email")}<p class="email-muted" style="margin:0 0 12px;color:#68757e;font-size:13px;line-height:1.6">If you did not request this change, you can safely ignore this email and your current email address will remain unchanged.</p>${fallbackLink(confirmationUrl)}`
    }),
    reauthentication: identityEmail({
      year,
      subject: "Your Altitutor verification code",
      previewText: "Use this code to confirm your identity.",
      heading: "Confirm your identity",
      bodyText: `Use this verification code to complete the security-sensitive action you requested:

${token}

This code expires in 1 hour.`,
      bodyHtml: `<p class="email-copy" style="${copyStyle}">Use this verification code to complete the security-sensitive action you requested.</p>${codePanel("Verification code", token)}<p class="email-muted" style="${mutedStyle2}">This code expires in 1 hour. If you did not request it, you can safely ignore this email. Your account remains secure.</p>`
    })
  };
}

// src/edge-delivery.ts
async function deliverEdgeEmail(input) {
  const fetchImpl = input.fetchImpl ?? fetch;
  const response = await fetchImpl("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${input.apiKey}`,
      "Content-Type": "application/json",
      ...input.idempotencyKey ? { "Idempotency-Key": input.idempotencyKey.slice(0, 256) } : {}
    },
    body: JSON.stringify({
      from: input.email.from,
      reply_to: input.email.replyTo,
      to: input.to,
      subject: input.email.subject,
      html: input.email.html,
      text: input.email.text,
      ...input.headers ? { headers: input.headers } : {},
      ...input.tags ? { tags: input.tags } : {}
    })
  });
  if (!response.ok) {
    throw new Error(
      `Resend ${response.status}: ${await response.text()}`
    );
  }
  const payload = await response.json();
  return {
    providerMessageId: typeof payload.id === "string" ? payload.id : null
  };
}
export {
  EMAIL_SENDERS,
  buildAuthEmails,
  buildBookingCancelledEmail,
  buildBookingChangedEmail,
  buildBookingConfirmationEmail,
  buildContactRequestEmail,
  buildInvitationEmail,
  buildInvoiceNotificationEmail,
  buildRegistrationEmail,
  deliverEdgeEmail,
  escapeEmailHtml,
  renderEmail,
  renderEmailButton,
  renderEmailPanel
};
