'use client';
import {useCallback,useEffect,useState} from 'react';
import {Button,Input,Label} from '@altitutor/ui';
import {DEFAULT_FLASHCARD_STUDY_PRESET_ID} from '@altitutor/shared';

type Preset={id:string;name:string;is_default:boolean;archived_at:string|null};type Version={preset_id:string;version:number;desired_retention:number;learning_steps_minutes:number[];relearning_steps_minutes:number[];minimum_lapse_interval_days:number;learn_ahead_minutes:number;leech_threshold:number;leech_reminder_interval:number;fsrs_parameters:number[]};type Subject={id:string;name:string;short_name:string};
export function FlashcardPresetSettings(){const [data,setData]=useState<{presets:Preset[];versions:Version[];assignments:{subject_id:string;preset_id:string}[];subjects:Subject[]}|null>(null);const [name,setName]=useState('');
 const [resumeStudentId,setResumeStudentId]=useState('');const [resumeCardId,setResumeCardId]=useState('');
 const load=useCallback(()=>fetch('/api/flashcard-study-presets').then(r=>r.json()).then(r=>setData(r.data)),[]);useEffect(()=>{void load();},[load]);
 const latest=(id:string)=>data?.versions.filter(v=>v.preset_id===id).sort((a,b)=>b.version-a.version)[0];
 const create=async()=>{const base=latest(DEFAULT_FLASHCARD_STUDY_PRESET_ID);if(!base||!name.trim())return;await fetch('/api/flashcard-study-presets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',name,config:{desiredRetention:Number(base.desired_retention),learningStepsMinutes:base.learning_steps_minutes,relearningStepsMinutes:base.relearning_steps_minutes,minimumLapseIntervalDays:base.minimum_lapse_interval_days,learnAheadMinutes:base.learn_ahead_minutes,leechThreshold:base.leech_threshold,leechReminderInterval:base.leech_reminder_interval,fsrsParameters:base.fsrs_parameters}})});setName('');await load();};
 const assign=async(subjectId:string,presetId:string)=>{await fetch('/api/flashcard-study-presets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'assign',subjectId,presetId})});await load();};
 const revise=async(preset:Preset)=>{const current=latest(preset.id);if(!current)return;const retention=window.prompt('Desired retention (0.80–0.95)',String(current.desired_retention));if(retention===null)return;const learning=window.prompt('Learning steps in minutes, comma-separated (blank for FSRS short-term)',current.learning_steps_minutes.join(','));if(learning===null)return;const relearning=window.prompt('Relearning steps in minutes, comma-separated',current.relearning_steps_minutes.join(','));if(relearning===null)return;const parse=(value:string)=>value.trim()?value.split(',').map(Number):[];await fetch('/api/flashcard-study-presets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'revise',presetId:preset.id,config:{desiredRetention:Number(retention),learningStepsMinutes:parse(learning),relearningStepsMinutes:parse(relearning),minimumLapseIntervalDays:current.minimum_lapse_interval_days,learnAheadMinutes:current.learn_ahead_minutes,leechThreshold:current.leech_threshold,leechReminderInterval:current.leech_reminder_interval,fsrsParameters:current.fsrs_parameters}})});await load();};
 const archive=async(preset:Preset)=>{if(preset.is_default||!window.confirm(`Archive ${preset.name}? Existing assignments continue to resolve it.`))return;await fetch('/api/flashcard-study-presets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'archive',presetId:preset.id})});await load();};
 return <div className="space-y-6 p-6"><div><h1 className="text-3xl font-bold">Flashcard study presets</h1><p className="text-muted-foreground">Versioned FSRS settings assigned at Subject level. Platform limits and queue policy are global.</p></div>
 <div className="flex max-w-xl gap-2"><div className="flex-1"><Label htmlFor="preset-name">Copy Default as</Label><Input id="preset-name" value={name} onChange={e=>setName(e.target.value)} placeholder="Preset name"/></div><Button className="self-end" onClick={()=>void create()}>Create preset</Button></div>
 <div className="grid gap-3 md:grid-cols-2">{data?.presets.map(preset=><div key={preset.id} className="rounded-lg border p-4"><div className="flex justify-between"><strong>{preset.name}</strong><span className="text-sm text-muted-foreground">v{latest(preset.id)?.version}</span></div><p className="text-sm text-muted-foreground">Retention {latest(preset.id)?.desired_retention} · Learn {latest(preset.id)?.learning_steps_minutes.join(', ')}m · Relearn {latest(preset.id)?.relearning_steps_minutes.join(', ')}m</p><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>void revise(preset)}>Create revision</Button>{!preset.is_default&&!preset.archived_at?<Button size="sm" variant="ghost" onClick={()=>void archive(preset)}>Archive</Button>:null}</div></div>)}</div>
 <div className="space-y-3">{data?.subjects.map(subject=><div key={subject.id} className="flex items-center justify-between rounded-lg border p-4"><span>{subject.name}</span><select className="rounded border bg-background p-2" value={data.assignments.find(a=>a.subject_id===subject.id)?.preset_id??DEFAULT_FLASHCARD_STUDY_PRESET_ID} onChange={e=>void assign(subject.id,e.target.value)}>{data.presets.filter(p=>!p.archived_at).map(p=><option key={p.id} value={p.id}>{p.name} (v{latest(p.id)?.version})</option>)}</select></div>)}</div>
 <div className="max-w-2xl rounded-lg border p-4"><h2 className="font-semibold">Resume a student card</h2><p className="text-sm text-muted-foreground">Admin recovery for a student-suspended card.</p><div className="mt-3 flex gap-2"><Input aria-label="Student ID" placeholder="Student UUID" value={resumeStudentId} onChange={e=>setResumeStudentId(e.target.value)}/><Input aria-label="Review card ID" placeholder="Review card UUID" value={resumeCardId} onChange={e=>setResumeCardId(e.target.value)}/><Button onClick={()=>void fetch(`/api/flashcard-review-cards/${resumeCardId}/resume`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId:resumeStudentId})})}>Resume</Button></div></div></div>;
}
