'use client';

import { useEffect, useMemo, useState } from 'react';
import { Button, Checkbox, Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, Label, SearchableSelect } from '@altitutor/ui';

type Enrolment = { id: string; class_id: string; classes: { id: string; short_name: string | null; long_name: string | null } | null };
type Session = { id: string; class_id: string; start_at: string; short_name: string | null; long_name: string | null };

export function StudentExitRequestDialog({ open, onOpenChange, studentId, studentName, workflowKey, onCreated }: { open: boolean; onOpenChange: (open: boolean) => void; studentId: string; studentName: string; workflowKey: 'student_unenrolment' | 'student_discontinuation'; onCreated?: () => void }) {
  const [enrolments, setEnrolments] = useState<Enrolment[]>([]); const [sessions, setSessions] = useState<Session[]>([]);
  const [selected, setSelected] = useState<Record<string, string>>({}); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [link, setLink] = useState<string | null>(null);
  useEffect(() => { if (!open) return; setLink(null); setError(null); setSelected({}); fetch(`/api/forms/exit-requests?studentId=${studentId}`).then(async r => { const json = await r.json(); if (!r.ok) throw new Error(json.error ?? 'Could not load active classes'); setEnrolments(json.enrolments ?? []); setSessions(json.sessions ?? []); }).catch(e => setError(e.message)); }, [open, studentId]);
  const selectedRows = useMemo(() => enrolments.filter(row => selected[row.id]), [enrolments, selected]);
  const submit = async () => { if (!selectedRows.length) return setError('Select at least one class and its final session.'); setSaving(true); setError(null); try { const res = await fetch('/api/forms/exit-requests', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ studentId, workflowKey, enrolments: selectedRows.map(row => ({ classesStudentsId: row.id, finalSessionAt: selected[row.id], unenrolledAt: new Date(new Date(selected[row.id]).getTime() + 1).toISOString() })) }) }); const json = await res.json(); if (!res.ok) throw new Error(json.error ?? 'Could not create exit request'); const nextLink = `${window.location.origin}/unenrol/${json.token}`; setLink(nextLink); onCreated?.(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create exit request'); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="md:max-w-2xl"><DialogHeader><DialogTitle>{workflowKey === 'student_discontinuation' ? 'Request discontinuation' : 'Request class unenrolment'} for {studentName}</DialogTitle></DialogHeader>{link ? <div className="space-y-4"><p className="text-sm text-muted-foreground">The request is ready. Send this authenticated student link using the existing message composer.</p><div className="break-all rounded-md border bg-muted/30 p-3 text-sm">{link}</div><DialogFooter><Button type="button" onClick={() => navigator.clipboard.writeText(link)}>Copy link</Button><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Done</Button></DialogFooter></div> : <div className="space-y-4">{enrolments.map(row => { const classSessions = sessions.filter(session => session.class_id === row.class_id); const value = selected[row.id] ?? ''; return <div key={row.id} className="rounded-md border p-3"><div className="flex items-center gap-3"><Checkbox checked={Boolean(value)} onCheckedChange={checked => setSelected(current => { const next = { ...current }; if (checked) next[row.id] = classSessions[0]?.start_at ?? ''; else delete next[row.id]; return next; })}/><Label>{row.classes?.long_name ?? row.classes?.short_name ?? 'Class'}</Label></div>{value ? <div className="mt-3"><SearchableSelect items={classSessions} value={classSessions.find(s => s.start_at === value) ?? null} onValueChange={session => setSelected(current => ({ ...current, [row.id]: session?.start_at ?? '' }))} getItemId={s => s.id} getItemLabel={s => new Date(s.start_at).toLocaleString('en-AU')} placeholder="Select final session" trigger={<Button type="button" variant="outline" className="w-full justify-start">{new Date(value).toLocaleString('en-AU')}</Button>} /></div> : null}{value && !classSessions.length ? <p className="mt-2 text-sm text-destructive">No future session is available for this class.</p> : null}</div>; })}{error ? <p className="text-sm text-destructive">{error}</p> : null}<DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="button" disabled={saving} onClick={submit}>{saving ? 'Creating…' : 'Create request'}</Button></DialogFooter></div>}</DialogContent></Dialog>;
}
