export const ucatKeys = {
  all: ['ucat'] as const,
  access: () => [...ucatKeys.all, 'access'] as const,
  sections: () => [...ucatKeys.all, 'sections'] as const,
  categories: () => [...ucatKeys.all, 'categories'] as const,
  tags: () => [...ucatKeys.all, 'tags'] as const,
  tagQuestions: (tagId: string) => [...ucatKeys.tags(), tagId, 'questions'] as const,
  questions: (mode: 'default' | 'generated' | 'all' = 'default') =>
    [...ucatKeys.all, 'questions', mode] as const,
  question: (id: string) => [...ucatKeys.all, 'question', id] as const,
  questionStemTypes: () => [...ucatKeys.questions('all'), 'stem-types'] as const,
  stemCatalog: () => [...ucatKeys.questions('all'), 'stem-catalog'] as const,
  sets: () => [...ucatKeys.all, 'sets'] as const,
  set: (id: string) => [...ucatKeys.sets(), id] as const,
  mocks: () => [...ucatKeys.all, 'mocks'] as const,
  mock: (id: string) => [...ucatKeys.mocks(), id] as const,
  students: () => [...ucatKeys.all, 'students'] as const,
  student: (id: string) => [...ucatKeys.students(), id] as const,
  classes: () => [...ucatKeys.all, 'classes'] as const,
  classSessions: (classId: string) => [...ucatKeys.classes(), classId, 'sessions'] as const,
  sessionResources: (sessionId: string) => [...ucatKeys.classes(), 'session', sessionId, 'resources'] as const,
  reconciliation: () => [...ucatKeys.all, 'reconciliation'] as const,
  learningModules: (kind?: string) => [...ucatKeys.all, 'learning-modules', kind ?? 'all'] as const,
  learningModule: (id: string) => [...ucatKeys.all, 'learning-module', id] as const,
  learningModuleBlocks: (moduleId: string) => [...ucatKeys.learningModule(moduleId), 'blocks'] as const,
  skillTrainerSets: (trainerKey?: string) =>
    [...ucatKeys.all, 'skill-trainer-sets', trainerKey ?? 'all'] as const,
  skillTrainerSet: (id: string) => [...ucatKeys.all, 'skill-trainer-set', id] as const,
  skillTrainerSetItems: (setId: string) => [...ucatKeys.skillTrainerSet(setId), 'items'] as const,
  skillTrainers: () => [...ucatKeys.all, 'skill-trainers'] as const,
}
