import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { build } from "esbuild";
import { buildAuthEmails, type AuthEmailName } from "../src";

const names: AuthEmailName[] = [
  "confirmation",
  "invite",
  "magic_link",
  "recovery",
  "email_change",
  "reauthentication",
];

const generatedNotice =
  "<!-- Generated by @altitutor/email. Edit packages/email/src/auth-emails.ts instead. -->\n";

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const root = resolve(__dirname, "../../../..");
  const outputDirectory = resolve(root, "supabase/templates");
  const emails = buildAuthEmails({ year: "__CURRENT_YEAR__" });
  let hasDrift = false;

  for (const name of names) {
    const path = resolve(outputDirectory, `${name}.html`);
    const expected = generatedNotice + emails[name].html + "\n";

    if (check) {
      const actual = await readFile(path, "utf8").catch(() => "");
      if (actual !== expected) {
        hasDrift = true;
        console.error(`Generated Auth template is stale: ${path}`);
      }
    } else {
      await writeFile(path, expected, "utf8");
    }
  }

  const edgePath = resolve(
    root,
    "supabase/functions/_shared/email.generated.ts",
  );
  const edgeBuild = await build({
    entryPoints: [resolve(root, "packages/email/src/index.ts")],
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    write: false,
    banner: {
      js: "// Generated by @altitutor/email. Edit packages/email/src instead.",
    },
  });
  const edgeExpected = edgeBuild.outputFiles[0]?.text;
  if (!edgeExpected) {
    throw new Error("Email Edge artifact generation produced no output");
  }

  if (check) {
    const edgeActual = await readFile(edgePath, "utf8").catch(() => "");
    if (edgeActual !== edgeExpected) {
      hasDrift = true;
      console.error(`Generated email Edge artifact is stale: ${edgePath}`);
    }
  } else {
    await writeFile(edgePath, edgeExpected, "utf8");
  }

  if (hasDrift) {
    process.exitCode = 1;
  } else {
    console.log(
      check
        ? "Generated Auth and Edge email artifacts match the shared module."
        : "Generated Auth and Edge email artifacts from the shared module.",
    );
  }
}

void main();
