-- =============================================================================
-- UCAT skill trainer generated Find the Word items from Wikipedia lead extracts
-- =============================================================================
-- Generated by apps/tutor-web/scripts/generate-ucat-find-word-wikipedia-seed.ts
-- Seed: 20260702
-- Batch: 1
-- Mode: overwrite
--
-- Wikipedia text is licensed CC BY-SA 4.0. Each item stores source metadata
-- including title, page id, revision id where available, source URL, and retrieval time.
-- Use --batch N to generate a non-overlapping UUID range.
-- Mode overwrite updates rows in this batch; mode make-new leaves existing rows untouched.
-- =============================================================================

INSERT INTO public.ucat_skill_trainer_items (
  id,
  skill_trainer_id,
  content,
  is_active,
  approval_status,
  approved_at
)
VALUES
  (
    'd1000001-0000-4000-8000-100100000001',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Apollo 11 (July 16–24, 1969) was the American spaceflight that first landed humans on the Moon, and the fifth crewed mission of NASA''s Apollo program. The mission was crewed by Commander Neil Armstrong, Command Module Pilot Michael Collins, and Lunar Module Pilot Edwin \"Buzz\" Aldrin, all of whom were on their second and final spaceflight."}]}]},"keywords":[{"id":"kw1","text":"Pilot"},{"id":"kw2","text":"Module"},{"id":"kw3","text":"American"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Apollo 11","pageid":662,"revision_id":1357361725,"url":"https://en.wikipedia.org/wiki/Apollo_11","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000002',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Ancient Egypt was a cradle of civilization concentrated along the lower reaches of the Nile River in the northeastern corner of Africa. It emerged from prehistoric Egypt around 3150 BC (according to conventional Egyptian chronology), when Upper and Lower Egypt were united by Menes, who is believed by the majority of Egyptologists to have been the same person as Narmer."}]},{"type":"paragraph","content":[{"type":"text","text":"The history of ancient Egypt unfolded as a series of stable kingdoms interspersed by the \"Intermediate Periods\" of relative instability. These stable kingdoms existed in one of three periods: the Old Kingdom of the Early Bronze Age; the Middle Kingdom of the Middle Bronze Age; or the New Kingdom of the Late Bronze Age."}]}]},"keywords":[{"id":"kw1","text":"3150"},{"id":"kw2","text":"Kingdom"},{"id":"kw3","text":"Late"},{"id":"kw4","text":"Age"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Ancient Egypt","pageid":874,"revision_id":1361946927,"url":"https://en.wikipedia.org/wiki/Ancient_Egypt","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000003',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Augusta Ada King, Countess of Lovelace (née Byron; 10 December 1815 – 27 November 1852), also known as Ada Lovelace, was an English mathematician and writer chiefly known for work on Charles Babbage''s proposed mechanical general-purpose computer, the analytical engine. She was the first to recognise the machine had applications beyond pure calculation."}]},{"type":"paragraph","content":[{"type":"text","text":"Lovelace is often considered the first computer programmer. Lovelace was the only legitimate child of poet Lord Byron and reformer Anne Isabella Milbanke. Lord Byron separated from his wife a month after Ada was born, and died when she was eight. Although often ill in childhood, Lovelace pursued her studies assiduously. She married William King in 1835."}]}]},"keywords":[{"id":"kw1","text":"Lord"},{"id":"kw2","text":"Lovelace"},{"id":"kw3","text":"Ada"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Ada Lovelace","pageid":974,"revision_id":1360639004,"url":"https://en.wikipedia.org/wiki/Ada_Lovelace","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000004',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Adelaide ( AD-il-ayd; Kaurna: Tarndanya [ˈd̪̥aɳɖaɲa]) is the capital and most populous city of South Australia, as well as the fifth-most populous city in Australia. The name \"Adelaide\" may refer to either Greater Adelaide (including the Adelaide Hills) or the Adelaide city centre; the demonym Adelaidean is used to denote the city and the residents of Adelaide."}]},{"type":"paragraph","content":[{"type":"text","text":"The traditional owners of the Adelaide region are the Kaurna, with the name Tarndanya referring to the area of the city centre and surrounding Park Lands, in the Kaurna language. Adelaide is situated on the Adelaide Plains north of the Fleurieu Peninsula, between the Gulf St Vincent in the west and the Mount Lofty Ranges in the east."}]}]},"keywords":[{"id":"kw1","text":"Mount"},{"id":"kw2","text":"Ranges"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Adelaide","pageid":1148,"revision_id":1361466063,"url":"https://en.wikipedia.org/wiki/Adelaide","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000005',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Alan Mathison Turing (; 23 June 1912 – 7 June 1954) was an English mathematician, computer scientist, logician, cryptanalyst, philosopher and theoretical biologist."}]},{"type":"paragraph","content":[{"type":"text","text":"He was highly influential in the development of theoretical computer science, providing a formalisation of the concepts of algorithm and computation with the Turing machine, which can be considered a model of a general-purpose computer. Turing is widely considered to be the father of theoretical computer science. Born in London, Turing was raised in southern England."}]}]},"keywords":[{"id":"kw1","text":"23 June 1912"},{"id":"kw2","text":"June"},{"id":"kw3","text":"considered"},{"id":"kw4","text":"London"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Alan Turing","pageid":1208,"revision_id":1362088307,"url":"https://en.wikipedia.org/wiki/Alan_Turing","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000006',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The French Revolution was a period of political and societal change in France that began with the Estates General of 1789 and ended with the Coup of 18 Brumaire on 9 November 1799. Many of the revolution''s ideas are considered fundamental principles of liberal democracy, and its values remain central to modern French political discourse."}]},{"type":"paragraph","content":[{"type":"text","text":"It was caused by a combination of social, political, and economic factors which the existing regime proved unable to manage. Financial crisis and widespread social distress led to the convocation of the Estates General in May 1789, its first meeting since 1614. The representatives of the Third Estate broke away and re-constituted themselves as a National Assembly in June."}]}]},"keywords":[{"id":"kw1","text":"9 November 1799"},{"id":"kw2","text":"1614"},{"id":"kw3","text":"Estates"},{"id":"kw4","text":"French"},{"id":"kw5","text":"June"}],"difficulty":"hard","source":{"provider":"wikipedia","title":"French Revolution","pageid":11188,"revision_id":1360777297,"url":"https://en.wikipedia.org/wiki/French_Revolution","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000007',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Sir Isaac Newton ( ; (1643-01-04)4 January 1643 [O. S. 25 December 1642] – 31 March [O. S. 20 March] 1727) was an English polymath who was a mathematician, physicist, astronomer, alchemist, theologian, author and inventor. He was a key figure in the Scientific Revolution and the Enlightenment that followed."}]},{"type":"paragraph","content":[{"type":"text","text":"His book Philosophiæ Naturalis Principia Mathematica (Mathematical Principles of Natural Philosophy), first published in 1687, achieved the first great unification in physics and established classical mechanics."}]}]},"keywords":[{"id":"kw1","text":"December"},{"id":"kw2","text":"Philosophi"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Isaac Newton","pageid":14627,"revision_id":1362116224,"url":"https://en.wikipedia.org/wiki/Isaac_Newton","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000008',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Industrial Revolution, sometimes called the First Industrial Revolution in contrast to the subsequent Second Industrial Revolution, was a transitional period of the global economy toward more widespread, efficient and stable manufacturing processes, succeeding the Second Agricultural Revolution."}]},{"type":"paragraph","content":[{"type":"text","text":"Beginning in Great Britain around 1760, the Industrial Revolution had spread to continental Europe and the United States by about 1840. Economic historians agree that the onset of the Industrial Revolution is the most important event in human history, comparable only to the adoption of agriculture with respect to material advancement."}]}]},"keywords":[{"id":"kw1","text":"States"},{"id":"kw2","text":"Revolution"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Industrial Revolution","pageid":14914,"revision_id":1360889925,"url":"https://en.wikipedia.org/wiki/Industrial_Revolution","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000009',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The International Space Station (ISS) is a space station in low Earth orbit (LEO). It is the product of the International Space Station program and is operated by five partner space agencies: NASA (United States), Roscosmos (Russia), ESA (Europe), JAXA (Japan), and CSA (Canada)."}]},{"type":"paragraph","content":[{"type":"text","text":"It is the first space station built, maintained and crewed through international cooperation and the largest human spacecraft ever constructed. It is an orbital research station, where scientific experiments in microgravity are conducted and the space environment is studied. Since 2 November 2000, it has hosted the longest continuous presence of humans in space."}]}]},"keywords":[{"id":"kw1","text":"Europe"},{"id":"kw2","text":"Space"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"International Space Station","pageid":15043,"revision_id":1361768129,"url":"https://en.wikipedia.org/wiki/International_Space_Station","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000000a',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Maria Salomea Skłodowska Curie (Polish: [ˈmarja salɔˈmɛa skwɔˈdɔfska kiˈri] ; née Skłodowska; 7 November 1867 – 4 July 1934), better known as Marie Curie ( KURE-ee; French: [maʁi kyʁi] ), was a Polish and naturalised-French physicist and chemist."}]},{"type":"paragraph","content":[{"type":"text","text":"She shared the 1903 Nobel Prize in Physics with her husband, Pierre Curie, \"for their joint researches on the radioactivity phenomena discovered by Professor Henri Becquerel\". She won the 1911 Nobel Prize in Chemistry \"[for] the discovery of the elements radium and polonium, by the isolation of radium and the study of the nature and compounds of this remarkable element\"."}]}]},"keywords":[{"id":"kw1","text":"Physics"},{"id":"kw2","text":"Chemistry"},{"id":"kw3","text":"Nobel"},{"id":"kw4","text":"Professor"},{"id":"kw5","text":"Curie"}],"difficulty":"hard","source":{"provider":"wikipedia","title":"Marie Curie","pageid":20408,"revision_id":1361218051,"url":"https://en.wikipedia.org/wiki/Marie_Curie","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000000b',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Magna Carta (Medieval Latin for \"Great Charter\"), sometimes spelled Magna Charta, is a royal charter of rights sealed by King John of England at Runnymede, near Windsor, on 15 June 1215."}]},{"type":"paragraph","content":[{"type":"text","text":"First drafted by the Archbishop of Canterbury, Cardinal Stephen Langton, to make peace between the unpopular king and a group of rebel barons who demanded that the King confirm the Charter of Liberties, it promised the protection of church rights, protection for the barons from illegal imprisonment, access to swift and impartial justice, and limitations on feudal payments to the Crown, to be implemented through a council of 25 barons."}]}]},"keywords":[{"id":"kw1","text":"Cardinal"},{"id":"kw2","text":"25"},{"id":"kw3","text":"Runnymede"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Magna Carta","pageid":20958,"revision_id":1358721085,"url":"https://en.wikipedia.org/wiki/Magna_Carta","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000000c',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Roman Empire was a state that dominated the Mediterranean and much of Europe, Western Asia, and North Africa during the classical period. The Roman Republic had previously conquered most of these territories, which later came under permanent single-person rule following Octavian''s rise to power and the establishment of the Augustan Principate in 27 BC."}]},{"type":"paragraph","content":[{"type":"text","text":"By the late 3rd century AD, the empire had been divided many times. The later Western Roman Empire collapsed in 476 AD, whereas the Eastern Roman Empire (also known as the Byzantine Empire) persisted until the fall of Constantinople in 1453. By 100 BC, the city of Rome had expanded its rule from the Italian peninsula to most of the Mediterranean and beyond."}]}]},"keywords":[{"id":"kw1","text":"Empire"},{"id":"kw2","text":"100"},{"id":"kw3","text":"1453"},{"id":"kw4","text":"476"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Roman Empire","pageid":25507,"revision_id":1360341927,"url":"https://en.wikipedia.org/wiki/Roman_Empire","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000000d',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"South Australia (commonly abbreviated as SA) is a state in the southern central part of Australia. With a total land area of 984,314 square kilometres (380,046 sq mi), it is the fourth-largest of Australia''s states and territories by area, which includes some of the most arid parts of the continent. With 1."}]},{"type":"paragraph","content":[{"type":"text","text":"9 million people as of June 2025, it is the 17th-largest subdivision in the world and the fifth-largest in Australasia. It is the second-most highly centralised state in the nation after Western Australia, with more than 67% of South Australians living in the capital Adelaide or its environs."}]}]},"keywords":[{"id":"kw1","text":"380,046"},{"id":"kw2","text":"2025"},{"id":"kw3","text":"June"},{"id":"kw4","text":"Australia"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"South Australia","pageid":26716,"revision_id":1361727171,"url":"https://en.wikipedia.org/wiki/South_Australia","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000000e',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Sydney Opera House is a multi-venue performing arts centre in Sydney, New South Wales, Australia. Located on the foreshore of Sydney Harbour, it is widely regarded as one of the world''s most famous and distinctive buildings, and a masterpiece of 20th-century architecture."}]},{"type":"paragraph","content":[{"type":"text","text":"Designed by Danish architect Jørn Utzon and completed by an Australian architectural team headed by Peter Hall, the building was formally opened by Queen Elizabeth II on 20 October 1973, 16 years after Utzon''s 1957 selection as winner of an international design competition."}]}]},"keywords":[{"id":"kw1","text":"Opera"},{"id":"kw2","text":"Elizabeth"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Sydney Opera House","pageid":28222,"revision_id":1359989632,"url":"https://en.wikipedia.org/wiki/Sydney_Opera_House","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000000f',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Hubble Space Telescope (HST or Hubble) is a space telescope that was launched into low Earth orbit in 1990 and remains in operation. It was not the first space telescope, but it is one of the largest and most versatile, renowned as a vital research tool and as a public relations boon for astronomy."}]},{"type":"paragraph","content":[{"type":"text","text":"The Hubble Space Telescope is named after astronomer Edwin Hubble and is one of NASA''s Great Observatories. The Space Telescope Science Institute (STScI) selects Hubble''s targets and processes the resulting data, while the Goddard Space Flight Center (GSFC) controls the spacecraft. Hubble features a 2."}]}]},"keywords":[{"id":"kw1","text":"Hubble"},{"id":"kw2","text":"NASA''s"},{"id":"kw3","text":"Science"},{"id":"kw4","text":"2"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Hubble Space Telescope","pageid":40203,"revision_id":1361712368,"url":"https://en.wikipedia.org/wiki/Hubble_Space_Telescope","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000010',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Great Barrier Reef is the world''s largest coral reef system, composed of over 2,900 individual reefs and 900 islands stretching for over 2,300 kilometres (1,400 mi) over an area of approximately 344,400 square kilometres (133,000 mi2)."}]},{"type":"paragraph","content":[{"type":"text","text":"The reef is located in the Coral Sea, off the coast of Queensland, Australia, separated from the coast by a channel 160 kilometres (100 mi) wide in places and over 61 metres (200 ft) deep. The Great Barrier Reef can be seen from outer space and is the world''s biggest single structure made by living organisms."}]}]},"keywords":[{"id":"kw1","text":"2,900"},{"id":"kw2","text":"160"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Great Barrier Reef","pageid":70983,"revision_id":1357848546,"url":"https://en.wikipedia.org/wiki/Great_Barrier_Reef","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000011',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Rosalind Elsie Franklin (25 July 1920 – 16 April 1958) was an English chemist and X-ray crystallographer. Her work was central to the understanding of the molecular structures of DNA (deoxyribonucleic acid), RNA (ribonucleic acid), viruses, coal, and graphite."}]},{"type":"paragraph","content":[{"type":"text","text":"Although her works on coal and viruses were appreciated in her lifetime, Franklin''s contributions to the discovery of the structure of DNA were largely unrecognised during her life, for which Franklin has been variously referred to as the \"wronged heroine\", the \"dark lady of DNA\", the \"forgotten heroine\", a \"feminist icon\", and the \"Sylvia Plath of molecular biology\"."}]}]},"keywords":[{"id":"kw1","text":"heroine"},{"id":"kw2","text":"Franklin"},{"id":"kw3","text":"DNA"},{"id":"kw4","text":"Sylvia"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Rosalind Franklin","pageid":90472,"revision_id":1358545736,"url":"https://en.wikipedia.org/wiki/Rosalind_Franklin","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000012',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Florence Nightingale (; 12 May 1820 – 13 August 1910) was an English social reformer, statistician and the founder of modern nursing. Nightingale came to prominence while serving as a manager and trainer of nurses during the Crimean War, in which she organised care for wounded soldiers at Constantinople."}]},{"type":"paragraph","content":[{"type":"text","text":"She significantly reduced death rates by improving hygiene and living standards. Nightingale gave nursing a favourable reputation and became an icon of Victorian culture, especially in the persona of \"The Lady with the Lamp\" making ward rounds for wounded soldiers at night."}]}]},"keywords":[{"id":"kw1","text":"Victorian"},{"id":"kw2","text":"Lamp"},{"id":"kw3","text":"Crimean"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Florence Nightingale","pageid":100127,"revision_id":1358730807,"url":"https://en.wikipedia.org/wiki/Florence_Nightingale","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000013',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Kangaroo Island (Kaurna: Karta Pintingga, lit. ''Island of the Dead''), known colloquially as KI, is Australia''s third-largest island, after Tasmania and Melville Island. It lies in the state of South Australia, 112 km (70 mi) southwest of Adelaide. Its closest point to the mainland is Snapper Point in Backstairs Passage, which is 13. 5 km (8. 4 mi) from the Fleurieu Peninsula."}]},{"type":"paragraph","content":[{"type":"text","text":"Receiving over 200,000 visitors annually, Kangaroo Island is one of Australia''s most popular travel destinations, and was ranked as the second-best travel destination globally by Lonely Planet in 2024."}]}]},"keywords":[{"id":"kw1","text":"Adelaide"},{"id":"kw2","text":"Backstairs"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Kangaroo Island","pageid":161773,"revision_id":1356039121,"url":"https://en.wikipedia.org/wiki/Kangaroo_Island","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000014',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Charles Robert Darwin ( DAR-win; 12 February 1809 – 19 April 1882) was an English naturalist, geologist, and biologist, widely known for his contributions to evolutionary biology. His proposition that all species of life have descended from a common ancestor is now generally accepted and considered a fundamental scientific concept."}]},{"type":"paragraph","content":[{"type":"text","text":"In a joint presentation with Alfred Russel Wallace, he introduced his scientific theory that this branching pattern of evolution resulted from a process he called natural selection, in which the struggle for existence has a similar effect to the artificial selection involved in selective breeding."}]}]},"keywords":[{"id":"kw1","text":"Russel"},{"id":"kw2","text":"1809"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Charles Darwin","pageid":8145410,"revision_id":1360793412,"url":"https://en.wikipedia.org/wiki/Charles_Darwin","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000015',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Eiffel Tower ( EYE-fəl; French: Tour Eiffel [tuʁ ɛfɛl] ) is a lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower from 1887 to 1889."}]},{"type":"paragraph","content":[{"type":"text","text":"Locally nicknamed \"La dame de fer\" (French for \"Iron Lady\") for its use of wrought iron, it was constructed as the centrepiece of the 1889 World''s Fair, and to crown the centennial anniversary of the French Revolution."}]}]},"keywords":[{"id":"kw1","text":"Revolution"},{"id":"kw2","text":"World''s"},{"id":"kw3","text":"EYE-fəl"},{"id":"kw4","text":"France"},{"id":"kw5","text":"1889"}],"difficulty":"hard","source":{"provider":"wikipedia","title":"Eiffel Tower","pageid":9232,"revision_id":1360653242,"url":"https://en.wikipedia.org/wiki/Eiffel_Tower","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000016',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The European Union (EU) is a political and economic union of 27 member states that are located primarily in Europe. A supranational union with a total area of 4,233,255 km2 (1,634,469 sq mi) and an estimated population of over 450 million as of 2025, its member states generated a nominal gross domestic product (GDP) of around €18."}]},{"type":"paragraph","content":[{"type":"text","text":"802 trillion in 2025, accounting for approximately one sixth of global economic output. The EU is often described as a sui generis political entity combining characteristics of both a federation and a confederation."}]}]},"keywords":[{"id":"kw1","text":"4,233,255"},{"id":"kw2","text":"2025"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"European Union","pageid":9317,"revision_id":1361991595,"url":"https://en.wikipedia.org/wiki/European_Union","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000017',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"An earthquake, also called a quake, tremor, or temblor, is the shaking of the Earth''s surface resulting from a sudden release of energy in the lithosphere that creates seismic waves."}]},{"type":"paragraph","content":[{"type":"text","text":"Earthquakes can range in intensity, from those so weak they cannot be felt, to those violent enough to propel objects and people into the air, damage critical infrastructure, and wreak destruction across entire cities. The seismic activity of an area is the frequency, type, and size of earthquakes experienced over a particular time."}]}]},"keywords":[{"id":"kw1","text":"seismic"},{"id":"kw2","text":"Earthquakes"},{"id":"kw3","text":"earthquake"},{"id":"kw4","text":"those"},{"id":"kw5","text":"Earth''s"}],"difficulty":"hard","source":{"provider":"wikipedia","title":"Earthquake","pageid":10106,"revision_id":1360651716,"url":"https://en.wikipedia.org/wiki/Earthquake","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000018',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The FIFA World Cup, also known as the FIFA Men''s World Cup, is an international association football competition among the senior men''s national teams of the members of the Fédération Internationale de Football Association (FIFA), the sport''s global governing body."}]},{"type":"paragraph","content":[{"type":"text","text":"The tournament has been held every four years since the inaugural tournament in 1930, with the exception of 1942 and 1946 due to World War II. The reigning champions are Argentina, who won their third title at the 2022 World Cup by defeating France."}]}]},"keywords":[{"id":"kw1","text":"France"},{"id":"kw2","text":"1946"},{"id":"kw3","text":"FIFA"},{"id":"kw4","text":"Fédération"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"FIFA World Cup","pageid":11370,"revision_id":1362115352,"url":"https://en.wikipedia.org/wiki/FIFA_World_Cup","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000019',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Jane Austen ( OST-in, AW-stin; 16 December 1775 – 18 July 1817) was an English writer known primarily for her six novels, which implicitly interpret, critique, and comment on the English landed gentry at the end of the 18th century. Austen''s plots often explore the dependence of women on marriage for the pursuit of favourable social standing and economic security."}]},{"type":"paragraph","content":[{"type":"text","text":"Her works are implicit critiques of the novels of sensibility of the second half of the 18th century and are part of the transition to 19th-century literary realism. Her use of social commentary, realism, wit, and irony have earned her acclaim amongst critics and scholars. Austen wrote major novels before the age of 22, but she was not published until she was 35."}]}]},"keywords":[{"id":"kw1","text":"18th"},{"id":"kw2","text":"Austen"},{"id":"kw3","text":"35"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Jane Austen","pageid":15782,"revision_id":1361713302,"url":"https://en.wikipedia.org/wiki/Jane_Austen","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000001a',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Louvre (French: Musée du Louvre [myze dy luvʁ] ) is a national art museum in Paris, France. It is located on the Right Bank of the Seine in the city''s 1st arrondissement (district) and home to some of the most canonical works of Western art, including the Mona Lisa, Venus de Milo, and Winged Victory."}]},{"type":"paragraph","content":[{"type":"text","text":"The museum is housed in the Louvre Palace, originally built in the late 12th to 13th century under Philip II. Remnants of the Medieval Louvre fortress are visible in the basement of the museum. Due to urban expansion, the fortress eventually lost its defensive function, and in 1546 Francis I converted it into the primary residence of the French kings."}]}]},"keywords":[{"id":"kw1","text":"Winged"},{"id":"kw2","text":"fortress"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Louvre","pageid":17546,"revision_id":1361363244,"url":"https://en.wikipedia.org/wiki/Louvre","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000001b',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Ludwig van Beethoven (baptised 17 December 1770 – 26 March 1827) was a German composer, conductor, and pianist."}]},{"type":"paragraph","content":[{"type":"text","text":"Regarded as one of the greatest composers in the history of Western music, he was mentored during the Classical period, and his musical style was a key driver of the transition to Romantic music, and the expansion of instrumental forms such as the symphony, the piano sonata and the string quartet."}]},{"type":"paragraph","content":[{"type":"text","text":"His compositions have attracted extraordinary casual and scholarly interest, and remain among the most performed in the world. Born in Bonn, Beethoven was a musical prodigy. He was initially taught intensively by his father, Johann van Beethoven, and later by Christian Gottlob Neefe."}]}]},"keywords":[{"id":"kw1","text":"Bonn"},{"id":"kw2","text":"Romantic"},{"id":"kw3","text":"Neefe"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Ludwig van Beethoven","pageid":17914,"revision_id":1362140907,"url":"https://en.wikipedia.org/wiki/Ludwig_van_Beethoven","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000001c',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Nile is a major north-flowing river in northeast Africa which empties into the Mediterranean Sea. At 7,088 kilometers (4,404 mi) long, it is the longest river in the world, although the volume of water it carries is much smaller than other major rivers such as the Amazon or the Congo."}]},{"type":"paragraph","content":[{"type":"text","text":"The Nile has played a central role in the environmental, economic, and cultural history of Africa for millennia. The Nile has two major tributaries: the White Nile and the Blue Nile. The White Nile is longer and is considered to be the headwaters, yet the Blue Nile contributes over twice the volume of the White Nile."}]}]},"keywords":[{"id":"kw1","text":"4,404"},{"id":"kw2","text":"Congo"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Nile","pageid":21244,"revision_id":1361112005,"url":"https://en.wikipedia.org/wiki/Nile","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000001d',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The modern Olympic Games (Olympics; French: Jeux olympiques) are among the biggest sporting events on Earth. They feature summer and winter sports events in which thousands of athletes from 206 countries and territories around the world participate in a variety of athletic competitions."}]},{"type":"paragraph","content":[{"type":"text","text":"The Olympic Games, open to both amateur and professional athletes, involve more than 200 teams, each team representing a sovereign state or territory. The Games often, but not always, substitute for any world championships during the year in which they take place. The Olympics are staged every four years."}]}]},"keywords":[{"id":"kw1","text":"Games"},{"id":"kw2","text":"Olympic"},{"id":"kw3","text":"200"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Olympic Games","pageid":22576,"revision_id":1361541554,"url":"https://en.wikipedia.org/wiki/Olympic_Games","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000001e',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Photosynthesis is a system of biological processes by which photopigment-bearing autotrophic organisms, such as most plants, algae and cyanobacteria, convert light energy — typically from sunlight — into the chemical energy necessary to fuel their metabolism."}]},{"type":"paragraph","content":[{"type":"text","text":"The term photosynthesis usually refers to oxygenic photosynthesis, a process that releases oxygen as a byproduct of water splitting."}]},{"type":"paragraph","content":[{"type":"text","text":"Photosynthetic organisms store the converted chemical energy within the bonds of intracellular organic compounds (complex compounds containing carbon), typically carbohydrates like sugars (mainly glucose, fructose and sucrose), starches, phytoglycogen and cellulose."}]}]},"keywords":[{"id":"kw1","text":"Photosynthesis"},{"id":"kw2","text":"typically"},{"id":"kw3","text":"compounds"},{"id":"kw4","text":"energy"},{"id":"kw5","text":"organisms"}],"difficulty":"hard","source":{"provider":"wikipedia","title":"Photosynthesis","pageid":24544,"revision_id":1358838651,"url":"https://en.wikipedia.org/wiki/Photosynthesis","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000001f',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Plate tectonics (from Latin tectonicus, from Ancient Greek τεκτονικός (tektonikós) ''pertaining to building'') is the scientific theory that Earth''s lithosphere comprises a number of large tectonic plates, which have been slowly moving since 3–4 billion years ago. The model builds on the concept of continental drift, an idea developed during the first decades of the 20th century."}]},{"type":"paragraph","content":[{"type":"text","text":"Plate tectonics came to be accepted by geoscientists after seafloor spreading was validated in the mid- to late 1960s. The processes that result in plates and shape Earth''s crust are called tectonics."}]}]},"keywords":[{"id":"kw1","text":"Ancient"},{"id":"kw2","text":"Earth''s"},{"id":"kw3","text":"20th"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Plate tectonics","pageid":24944,"revision_id":1362124384,"url":"https://en.wikipedia.org/wiki/Plate_tectonics","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000020',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The United Nations (UN) is a global intergovernmental organization established by the signing of the Charter of the United Nations on 26 June 1945 with the articulated mission of maintaining international peace and security, to develop friendly relations among states, to promote international cooperation, and to serve as a centre for harmonizing the actions of states in achieving those goals."}]},{"type":"paragraph","content":[{"type":"text","text":"The United Nations headquarters is located in New York City, with several other offices located in Geneva, Nairobi, Vienna and The Hague."}]}]},"keywords":[{"id":"kw1","text":"Geneva"},{"id":"kw2","text":"26 June 1945"},{"id":"kw3","text":"located"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"United Nations","pageid":31769,"revision_id":1362136515,"url":"https://en.wikipedia.org/wiki/United_Nations","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000021',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"A volcano is a vent or fissure in the crust of a planetary-mass object that allows hot lava, volcanic ash, and gases to escape from a magma chamber below the surface. On Earth, volcanoes are most often found where tectonic plates are diverging or converging, and because most of Earth''s plate boundaries are underwater, most volcanoes are found underwater."}]},{"type":"paragraph","content":[{"type":"text","text":"For example, a mid-ocean ridge, such as the Mid-Atlantic Ridge, has volcanoes caused by divergent tectonic plates whereas the Pacific Ring of Fire has volcanoes caused by convergent tectonic plates. Volcanoes resulting from divergent tectonic activity are usually non-explosive whereas those resulting from convergent tectonic activity cause violent eruptions."}]}]},"keywords":[{"id":"kw1","text":"divergent"},{"id":"kw2","text":"Fire"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Volcano","pageid":32571,"revision_id":1359260399,"url":"https://en.wikipedia.org/wiki/Volcano","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000022',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Vincent Willem van Gogh (Dutch: [ˈvɪnsɛnt ˈʋɪləɱ vɑŋ ˈɣɔx] ; 30 March 1853 – 29 July 1890) was a Dutch Post-Impressionist painter who is among the most famous and influential figures in the history of Western art. In just over a decade he created about 2,100 artworks, including around 860 oil paintings, most of them in the last two years of his life."}]},{"type":"paragraph","content":[{"type":"text","text":"They include landscapes, still lifes, portraits and self-portraits, and are characterised by bold colours and dramatic, impulsive and expressive brushwork that contributed to the foundations of modern art. His suicide at 37 followed years of mental illness and poverty. Born into an upper-middle-class family, Van Gogh drew as a child and was serious, quiet and thoughtful."}]}]},"keywords":[{"id":"kw1","text":"37"},{"id":"kw2","text":"Gogh"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Vincent van Gogh","pageid":32603,"revision_id":1361795563,"url":"https://en.wikipedia.org/wiki/Vincent_van_Gogh","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000023',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"William Shakespeare (c. 23 April 1564 – 23 April 1616) was an English playwright, poet and actor. He is widely regarded as the greatest writer in the English language and the world''s pre-eminent dramatist. He is often called England''s national poet and the \"Bard of Avon\" or simply \"the Bard\"."}]},{"type":"paragraph","content":[{"type":"text","text":"His extant works, including collaborations, consist of some 39 plays, 154 sonnets, three long narrative poems and a few other verses, some of uncertain authorship. His plays have been translated into every major living language and are performed more often than those of any other playwright."}]}]},"keywords":[{"id":"kw1","text":"Shakespeare"},{"id":"kw2","text":"England''s"},{"id":"kw3","text":"23"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"William Shakespeare","pageid":32897,"revision_id":1361141676,"url":"https://en.wikipedia.org/wiki/William_Shakespeare","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000024',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The World Health Organization (WHO) is a specialized agency of the United Nations (UN) which coordinates responses to international public health issues and emergencies. It is headquartered in Geneva, Switzerland, and has six regional offices and 150 field offices worldwide."}]},{"type":"paragraph","content":[{"type":"text","text":"Only sovereign states are eligible to join, and it is the largest intergovernmental health organization at the international level. The WHO''s stated purpose is to achieve the highest possible level of health for all the world''s people, defining health as \"a state of complete physical, mental and social well-being and not merely the absence of disease or infirmity.\""}]}]},"keywords":[{"id":"kw1","text":"150"},{"id":"kw2","text":"Organization"},{"id":"kw3","text":"Health"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"World Health Organization","pageid":33583,"revision_id":1361523187,"url":"https://en.wikipedia.org/wiki/World_Health_Organization","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000025',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Amazon rainforest, also called the Amazon jungle, Amazonia, or simply the Amazon, is a moist broadleaf tropical rainforest in the Amazon biome that covers most of the Amazon basin of South America. This basin encompasses 7 million km2 (2. 7 million sq mi), of which 6 million km2 (2. 3 million sq mi) are covered by the rainforest."}]},{"type":"paragraph","content":[{"type":"text","text":"This region includes territory belonging to nine nations and 3,344 indigenous territories. The majority of the forest, 60%, is in Brazil, followed by Peru with 13%, Colombia with 10%, and with minor amounts in Bolivia, Ecuador, French Guiana, Guyana, Suriname, and Venezuela."}]}]},"keywords":[{"id":"kw1","text":"7"},{"id":"kw2","text":"Guyana"},{"id":"kw3","text":"basin"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Amazon rainforest","pageid":48139,"revision_id":1360315914,"url":"https://en.wikipedia.org/wiki/Amazon_rainforest","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000026',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Mona Lisa is a half-length portrait painting by the Italian artist Leonardo da Vinci. Considered an archetypal masterpiece of the Italian Renaissance, it has been described as \"the best known, the most visited, the most written about, the most sung about, [and] the most parodied work of art in the world.\""}]},{"type":"paragraph","content":[{"type":"text","text":"The painting''s novel qualities include the subject''s enigmatic expression, the monumentality of the composition, the subtle modelling of forms, and the atmospheric illusionism. The painting has been traditionally considered to depict the Italian noblewoman Lisa del Giocondo. It is painted in oil on a white poplar panel. Leonardo never gave the painting to the Giocondo family."}]}]},"keywords":[{"id":"kw1","text":"Giocondo"},{"id":"kw2","text":"Italian"},{"id":"kw3","text":"Leonardo"},{"id":"kw4","text":"Lisa"},{"id":"kw5","text":"Renaissance"}],"difficulty":"hard","source":{"provider":"wikipedia","title":"Mona Lisa","pageid":70889,"revision_id":1361314090,"url":"https://en.wikipedia.org/wiki/Mona_Lisa","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000027',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Sahara (, ) is a desert spanning North Africa. With an area of 9,200,000 square kilometres (3,600,000 sq mi), it is the largest hot desert in the world and the third-largest desert overall, smaller only than the deserts of Antarctica and the northern Arctic."}]},{"type":"paragraph","content":[{"type":"text","text":"The name \"Sahara\" is derived from Arabic: صَحَارَى, romanized: ṣaḥārā /sˤaħaːraː/, a broken plural form of ṣaḥrā'' (صَحْرَاء /sˤaħraːʔ/), meaning \"desert\". The desert covers much of North Africa, excluding the fertile region on the Mediterranean Sea coast, the Atlas Mountains of the Maghreb, and the Nile Valley in Egypt and the Sudan."}]}]},"keywords":[{"id":"kw1","text":"Africa"},{"id":"kw2","text":"Arabic"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Sahara","pageid":325363,"revision_id":1362146759,"url":"https://en.wikipedia.org/wiki/Sahara","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000028',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Antarctica  is Earth''s southernmost and least-populated continent. Situated almost entirely south of the Antarctic Circle and surrounded by the Southern Ocean (also known as the Antarctic Ocean), it contains the geographic South Pole. Antarctica is the fifth-largest continent, being about 40% larger than Europe, and has an area of 14,200,000 km2 (5,500,000 sq mi)."}]},{"type":"paragraph","content":[{"type":"text","text":"Most of Antarctica is covered by the Antarctic ice sheet, with an average thickness of 1. 9 km (1. 2 mi). Antarctica is, on average, the coldest, driest, and windiest of the continents, and has the highest average elevation. It is mainly a polar desert, with annual precipitation of over 200 mm (8 in) along the coast and far less inland."}]}]},"keywords":[{"id":"kw1","text":"1"},{"id":"kw2","text":"5,500,000"},{"id":"kw3","text":"Antarctica"},{"id":"kw4","text":"200"},{"id":"kw5","text":"14,200,000"}],"difficulty":"hard","source":{"provider":"wikipedia","title":"Antarctica","pageid":18959138,"revision_id":1360951141,"url":"https://en.wikipedia.org/wiki/Antarctica","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000029',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Artificial intelligence (AI) is the capability of computational systems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making."}]},{"type":"paragraph","content":[{"type":"text","text":"It is a field of research in engineering, mathematics and computer science that develops and studies methods and software that enable machines to perceive their environment and use learning and intelligence to take actions that maximize their chances of achieving defined goals."}]}]},"keywords":[{"id":"kw1","text":"intelligence"},{"id":"kw2","text":"Artificial"},{"id":"kw3","text":"learning"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Artificial intelligence","pageid":1164,"revision_id":1361732815,"url":"https://en.wikipedia.org/wiki/Artificial_intelligence","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000002a',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Carbon dioxide is a chemical compound with the chemical formula CO2. It is made up of molecules that each have one carbon atom covalently double bonded to two oxygen atoms. It is found in a gas state at room temperature and at normally-encountered concentrations it is odorless."}]},{"type":"paragraph","content":[{"type":"text","text":"As the source of carbon in the carbon cycle, atmospheric CO2 is the primary carbon source for life on Earth. In the air, carbon dioxide is transparent to visible light but absorbs infrared radiation, acting as a greenhouse gas. Carbon dioxide is soluble in water and is found in groundwater, lakes, ice caps, and seawater."}]}]},"keywords":[{"id":"kw1","text":"Carbon"},{"id":"kw2","text":"found"},{"id":"kw3","text":"dioxide"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Carbon dioxide","pageid":5906,"revision_id":1360625447,"url":"https://en.wikipedia.org/wiki/Carbon_dioxide","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000002b',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Deoxyribonucleic acid (; DNA) is a polymer composed of two polynucleotide chains that coil around each other to form a double helix. The polymer carries genetic instructions for the development, functioning, growth and reproduction of all known organisms and many viruses. DNA and ribonucleic acid (RNA) are nucleic acids."}]},{"type":"paragraph","content":[{"type":"text","text":"Alongside proteins, lipids and complex carbohydrates (polysaccharides), nucleic acids are one of the four major types of macromolecules that are essential for all known forms of life. The two DNA strands are known as polynucleotides as they are composed of simpler monomeric units called nucleotides."}]}]},"keywords":[{"id":"kw1","text":"DNA"},{"id":"kw2","text":"nucleic"},{"id":"kw3","text":"acids"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"DNA","pageid":7955,"revision_id":1360900543,"url":"https://en.wikipedia.org/wiki/DNA","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000002c',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Gold is a chemical element; its chemical symbol is Au (from Latin aurum) and atomic number 79. In its pure form, it is a bright-metallic-yellow, dense, soft, malleable, and ductile metal. Chemically, gold is a transition metal, a group 11 element, and one of the noble metals."}]},{"type":"paragraph","content":[{"type":"text","text":"It is one of the least reactive chemical elements, being the second lowest in the reactivity series, with only platinum ranked as less reactive. Gold is solid under standard conditions. Gold often occurs as the free element (native state), as nuggets or grains, in rocks, veins, and alluvial deposits."}]}]},"keywords":[{"id":"kw1","text":"Gold"},{"id":"kw2","text":"metal"},{"id":"kw3","text":"reactive"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Gold","pageid":12240,"revision_id":1358452804,"url":"https://en.wikipedia.org/wiki/Gold","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000002d',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The Internet (or internet) is the global system of interconnected computer networks that uses the Internet protocol suite (TCP/IP) to communicate between networks and devices. It is a network of networks that comprises private, public, academic, business, and government networks of local to global scope, linked by electronic, wireless, and optical networking technologies."}]},{"type":"paragraph","content":[{"type":"text","text":"The Internet carries a vast range of information services and resources, such as the interlinked hypertext documents and applications of the World Wide Web (WWW), electronic mail, discussion groups, internet telephony, streaming media and file sharing."}]}]},"keywords":[{"id":"kw1","text":"Internet"},{"id":"kw2","text":"WWW"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Internet","pageid":14539,"revision_id":1361947836,"url":"https://en.wikipedia.org/wiki/Internet","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000002e',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Magnetic resonance imaging (MRI) is a medical imaging technique used in radiology to generate pictures of the anatomy and the physiological processes inside the body. MRI scanners use strong magnetic fields, magnetic field gradients, and radio waves to form images of the organs in the body."}]},{"type":"paragraph","content":[{"type":"text","text":"MRI does not involve X-rays or the use of ionizing radiation, which distinguishes it from computed tomography (CT) and positron emission tomography (PET) scans. MRI is a medical application of nuclear magnetic resonance (NMR) which can also be used for imaging in other NMR applications, such as NMR spectroscopy."}]}]},"keywords":[{"id":"kw1","text":"NMR"},{"id":"kw2","text":"resonance"},{"id":"kw3","text":"Magnetic"},{"id":"kw4","text":"imaging"},{"id":"kw5","text":"tomography"}],"difficulty":"hard","source":{"provider":"wikipedia","title":"Magnetic resonance imaging","pageid":19446,"revision_id":1360797248,"url":"https://en.wikipedia.org/wiki/Magnetic_resonance_imaging","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000002f',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The periodic table, also known as the periodic table of the elements, is an ordered arrangement of the chemical elements into rows (\"periods\") and columns (\"groups\"). An icon of chemistry, the periodic table is widely used in physics and other sciences."}]},{"type":"paragraph","content":[{"type":"text","text":"It is a depiction of the periodic law, which states that when the elements are arranged in order of their atomic numbers an approximate recurrence of their properties is evident. The table is divided into four roughly rectangular areas called blocks. Elements in the same group tend to show similar chemical characteristics."}]}]},"keywords":[{"id":"kw1","text":"table"},{"id":"kw2","text":"elements"},{"id":"kw3","text":"chemical"},{"id":"kw4","text":"periodic"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Periodic table","pageid":23053,"revision_id":1361891479,"url":"https://en.wikipedia.org/wiki/Periodic_table","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000030',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Penicillins (P, PCN or PEN) are a group of β-lactam antibiotics originally obtained from Penicillium moulds, principally P. chrysogenum and P. rubens. Most penicillins in clinical use are synthesised by P. chrysogenum using deep tank fermentation and then purified."}]},{"type":"paragraph","content":[{"type":"text","text":"A number of natural penicillins have been discovered, but only two purified compounds are in clinical use: penicillin G (intramuscular or intravenous use) and penicillin V (given by mouth). Penicillins were among the first medications to be effective against many bacterial infections caused by staphylococci and streptococci."}]}]},"keywords":[{"id":"kw1","text":"penicillin"},{"id":"kw2","text":"clinical"},{"id":"kw3","text":"purified"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Penicillin","pageid":23312,"revision_id":1354027758,"url":"https://en.wikipedia.org/wiki/Penicillin","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000031',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Renewable energy (also called green energy) is energy made from renewable natural resources that are replenished on a human timescale. The most widely used renewable energy types are solar energy, wind power, and hydropower. Bioenergy and geothermal power are also significant in some countries."}]},{"type":"paragraph","content":[{"type":"text","text":"Renewable energy installations can be large or small and are suited for both urban and rural areas. Renewable energy is often deployed together with further electrification. This has several benefits: electricity can move heat and vehicles efficiently and is clean at the point of consumption."}]}]},"keywords":[{"id":"kw1","text":"power"},{"id":"kw2","text":"Renewable"},{"id":"kw3","text":"energy"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Renewable energy","pageid":25784,"revision_id":1362143895,"url":"https://en.wikipedia.org/wiki/Renewable_energy","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000032',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"In microeconomics, supply and demand is an economic model of price determination in a market."}]},{"type":"paragraph","content":[{"type":"text","text":"It postulates that, holding all else equal, the unit price for a particular good or other traded item in a perfectly competitive market, will vary until it settles at the market-clearing price, where the quantity demanded equals the quantity supplied such that an economic equilibrium is achieved for price and quantity transacted."}]}]},"keywords":[{"id":"kw1","text":"market"},{"id":"kw2","text":"quantity"},{"id":"kw3","text":"supply"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Supply and demand","pageid":29664,"revision_id":1360794321,"url":"https://en.wikipedia.org/wiki/Supply_and_demand","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000033',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"A vaccine is a biological preparation that provides active acquired immunity to a particular infectious or malignant disease. The safety and effectiveness of vaccines has been widely studied and verified."}]},{"type":"paragraph","content":[{"type":"text","text":"A vaccine typically contains an agent that resembles a disease-causing microorganism and is often made from weakened or killed forms of the microbe, its toxins, or one of its surface proteins."}]},{"type":"paragraph","content":[{"type":"text","text":"The agent stimulates the immune system to recognize the agent as a threat, destroy it, and recognize further and destroy any of the microorganisms associated with that agent that it may encounter in the future."}]}]},"keywords":[{"id":"kw1","text":"recognize"},{"id":"kw2","text":"destroy"},{"id":"kw3","text":"vaccine"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Vaccine","pageid":32653,"revision_id":1354276133,"url":"https://en.wikipedia.org/wiki/Vaccine","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000034',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The World Wide Web (also known as WWW, W3, or simply the Web) is a global interconnected information system that enables content sharing over the Internet. It facilitates access to documents and other web resources according to specific rules of the Hypertext Transfer Protocol (HTTP)."}]},{"type":"paragraph","content":[{"type":"text","text":"The Web was invented by English computer scientist Tim Berners-Lee while at CERN in 1989 and opened to the public in 1993. It was conceived as a \"universal linked information system\". Documents and other media content are made available to the network through web servers and can be accessed by programs such as web browsers."}]}]},"keywords":[{"id":"kw1","text":"documents"},{"id":"kw2","text":"English"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"World Wide Web","pageid":33139,"revision_id":1361950532,"url":"https://en.wikipedia.org/wiki/World_Wide_Web","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000035',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"An X-ray is a form of high-energy electromagnetic radiation with a wavelength shorter than those of ultraviolet rays and longer than those of gamma rays."}]},{"type":"paragraph","content":[{"type":"text","text":"Roughly, X-rays have a wavelength ranging from 10 nanometers to 10 picometers, corresponding to frequencies in the range of 30 petahertz to 30 exahertz (3×1016 Hz to 3×1019 Hz) and photon energies in the range of 100 eV to 100 keV, respectively."}]},{"type":"paragraph","content":[{"type":"text","text":"X-rays were discovered in 1895 by the German scientist Wilhelm Conrad Röntgen, who named it X-radiation to signify an unknown type of radiation. X-rays can penetrate many solid substances such as construction materials and living tissue, so X-ray radiography is widely used in medical diagnostics (e. g. , checking for broken bones) and materials science (e. g."}]}]},"keywords":[{"id":"kw1","text":"10"},{"id":"kw2","text":"Wilhelm"},{"id":"kw3","text":"materials"},{"id":"kw4","text":"100"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"X-ray","pageid":34197,"revision_id":1360545105,"url":"https://en.wikipedia.org/wiki/X-ray","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000036',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"In economics, inflation is an increase in the average price of goods and services in terms of money. This increase is measured using a price index, typically a consumer price index (CPI). When the general price level rises, each unit of currency buys fewer goods and services; consequently, inflation corresponds to a reduction in the purchasing power of money."}]},{"type":"paragraph","content":[{"type":"text","text":"The opposite of inflation is deflation, a decrease in the general price level of goods and services. The common measure of inflation is the inflation rate, the annualized percentage change in a general price index."}]}]},"keywords":[{"id":"kw1","text":"general"},{"id":"kw2","text":"index"},{"id":"kw3","text":"level"},{"id":"kw4","text":"money"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Inflation","pageid":38286,"revision_id":1361742939,"url":"https://en.wikipedia.org/wiki/Inflation","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000037',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The human genome is a complete set of DNA sequences for each of the 22 autosomes and the two distinct sex chromosomes (X and Y). A small DNA molecule is found within individual mitochondria. These are usually treated separately as the nuclear genome and the mitochondrial genome. Human genomes include both genes and various other types of functional DNA elements."}]},{"type":"paragraph","content":[{"type":"text","text":"The latter is a diverse category that includes regulatory DNA scaffolding regions, telomeres, centromeres, and origins of replication. In addition, there are large numbers of transposable elements, endogenized viral DNA, non-functional pseudogenes and simple, highly repetitive sequences. Introns make up a large percentage of the human genome."}]}]},"keywords":[{"id":"kw1","text":"human"},{"id":"kw2","text":"elements"},{"id":"kw3","text":"sequences"},{"id":"kw4","text":"genome"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Human genome","pageid":42888,"revision_id":1361882302,"url":"https://en.wikipedia.org/wiki/Human_genome","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000038',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Machine learning (ML) is a field of study in artificial intelligence concerned with the development and study of statistical algorithms that can learn from data and generalize to unseen data, and thus perform tasks without being explicitly programmed."}]},{"type":"paragraph","content":[{"type":"text","text":"Advances in the field of deep learning have allowed neural networks, a class of statistical algorithms, to surpass many previous machine learning approaches in performance. Statistics and mathematical optimisation methods compose the foundations of machine learning."}]}]},"keywords":[{"id":"kw1","text":"learning"},{"id":"kw2","text":"statistical"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Machine learning","pageid":233488,"revision_id":1360517605,"url":"https://en.wikipedia.org/wiki/Machine_learning","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-100100000039',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Wind power is the use of wind energy to generate useful work. Historically, wind power was used by sails, windmills and windpumps, but today it is mostly used to generate electricity. This article deals only with wind power for electricity generation."}]},{"type":"paragraph","content":[{"type":"text","text":"Today, wind power is generated almost completely using wind turbines, generally grouped into wind farms and connected to the electrical grid. In 2025, wind supplied about 2,700 TWh of electricity, which was over 8% of world electricity. With about 100 GW added during 2021, mostly in China and the United States, global installed wind power capacity exceeded 800 GW."}]}]},"keywords":[{"id":"kw1","text":"power"},{"id":"kw2","text":"electricity"},{"id":"kw3","text":"States"},{"id":"kw4","text":"United"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Wind power","pageid":277289,"revision_id":1362144136,"url":"https://en.wikipedia.org/wiki/Wind_power","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000003a',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"An electric vehicle (EV) is a vehicle propelled mostly by electric power. EVs encompass road (cars, buses, trucks and personal transporters), rail (trains, trams and monorails), boats and submersibles, aircraft (fixed-wing and multirotors) and spacecraft. EVs originated in the late 19th century."}]},{"type":"paragraph","content":[{"type":"text","text":"Electricity was among the preferred methods for powering early motor vehicles because it was quieter, provided comfort, and ease of operation. However, its limited range hindered mass adoption throughout the 20th century."}]}]},"keywords":[{"id":"kw1","text":"vehicle"},{"id":"kw2","text":"electric"},{"id":"kw3","text":"20th"},{"id":"kw4","text":"19th"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Electric vehicle","pageid":279350,"revision_id":1361754248,"url":"https://en.wikipedia.org/wiki/Electric_vehicle","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000003b',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Solar power, also known as solar electricity, is the conversion of energy from sunlight into electricity, either directly using photovoltaics (PV) or indirectly using concentrated solar power. Solar panels use the photovoltaic effect to convert light into an electric current."}]},{"type":"paragraph","content":[{"type":"text","text":"Concentrated solar power systems use lenses or mirrors and solar tracking systems to focus a large area of sunlight to a hot spot, often to drive a steam turbine."}]}]},"keywords":[{"id":"kw1","text":"power"},{"id":"kw2","text":"Solar"}],"difficulty":"easy","source":{"provider":"wikipedia","title":"Solar power","pageid":13690575,"revision_id":1362144562,"url":"https://en.wikipedia.org/wiki/Solar_power","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  ),
  (
    'd1000001-0000-4000-8000-10010000003c',
    'a1000001-0000-4000-8000-000000000001',
    '{"passage":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Cryptography, or cryptology, is the practice and study of techniques for secure communication in the presence of adversarial behavior. More generally, cryptography is about constructing and analyzing protocols that prevent third parties or the public from reading private messages."}]},{"type":"paragraph","content":[{"type":"text","text":"Modern cryptography exists at the intersection of the disciplines of mathematics, computer science, information security, electrical engineering, digital signal processing, physics, and others. Core concepts related to information security (data confidentiality, data integrity, authentication and non-repudiation) are also central to cryptography."}]}]},"keywords":[{"id":"kw1","text":"information"},{"id":"kw2","text":"security"},{"id":"kw3","text":"Cryptography"}],"difficulty":"medium","source":{"provider":"wikipedia","title":"Cryptography","pageid":18934432,"revision_id":1360559240,"url":"https://en.wikipedia.org/wiki/Cryptography","license":"CC BY-SA 4.0","retrieved_at":"2026-07-02T11:41:21.820Z"}}'::jsonb,
    true,
    'approved',
    NOW()
  )
ON CONFLICT (id) DO UPDATE SET
  skill_trainer_id = EXCLUDED.skill_trainer_id,
  content = EXCLUDED.content,
  is_active = EXCLUDED.is_active,
  approval_status = EXCLUDED.approval_status,
  approved_at = EXCLUDED.approved_at,
  updated_at = NOW();

SELECT
  t.key,
  COUNT(i.id) AS generated_approved_active_items
FROM public.ucat_skill_trainers t
LEFT JOIN public.ucat_skill_trainer_items i
  ON i.skill_trainer_id = t.id
  AND i.id::text LIKE 'd1000001-0000-4000-8000-1001%'
  AND i.deleted_at IS NULL
  AND i.is_active = true
  AND i.approval_status = 'approved'
WHERE t.id = 'a1000001-0000-4000-8000-000000000001'
GROUP BY t.key, t.sort_order
ORDER BY t.sort_order;
