#!/usr/bin/env bash
# ============================================================
# Setup / sync CONNECTOR_SECRET + print-bridge .env
#
# - Ensures secrets/.env.{development,production} have CONNECTOR_SECRET
#   (reuses IMESSAGE_WEBHOOK_SECRET when present — shared with iMessage)
# - Writes ~/Github/print-bridge/.env from production secrets + Mac defaults
#
# Usage (from repo root or this directory):
#   ./secrets/scripts/setup-print-bridge-env.sh
#   ./secrets/scripts/setup-print-bridge-env.sh --env development
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(dirname "$SECRETS_DIR")"
PRINT_BRIDGE_DIR="${PRINT_BRIDGE_DIR:-$REPO_ROOT/../print-bridge}"

ENV_NAME="production"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)
      ENV_NAME="$2"
      shift 2
      ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

if [[ "$ENV_NAME" != "development" && "$ENV_NAME" != "production" ]]; then
  echo "ENV must be development or production" >&2
  exit 1
fi

ENV_FILE="$SECRETS_DIR/.env.$ENV_NAME"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE — copy from .env.$ENV_NAME.example first" >&2
  exit 1
fi

get_val() {
  local file="$1"
  local key="$2"
  local line
  line="$(rg -n "^${key}=" "$file" | head -1 || true)"
  if [[ -z "$line" ]]; then
    echo ""
    return
  fi
  echo "${line#*=}" | sed 's/^"//;s/"$//'
}

upsert_key() {
  local file="$1"
  local key="$2"
  local value="$3"
  if rg -q "^${key}=" "$file"; then
    # replace in place without printing value
    local tmp
    tmp="$(mktemp)"
    awk -v k="$key" -v v="$value" '
      BEGIN { done=0 }
      index($0, k "=") == 1 && !done { print k "=" v; done=1; next }
      { print }
      END { if (!done) print k "=" v }
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
  else
    printf '\n%s=%s\n' "$key" "$value" >> "$file"
  fi
}

IMESSAGE_WEBHOOK_SECRET="$(get_val "$ENV_FILE" "IMESSAGE_WEBHOOK_SECRET")"
CONNECTOR_SECRET="$(get_val "$ENV_FILE" "CONNECTOR_SECRET")"

if [[ -z "$CONNECTOR_SECRET" ]]; then
  if [[ -n "$IMESSAGE_WEBHOOK_SECRET" ]]; then
    CONNECTOR_SECRET="$IMESSAGE_WEBHOOK_SECRET"
    echo "CONNECTOR_SECRET was empty — copying from IMESSAGE_WEBHOOK_SECRET in .env.$ENV_NAME"
  else
    CONNECTOR_SECRET="$(openssl rand -hex 32)"
    echo "Generated new CONNECTOR_SECRET (openssl rand -hex 32) for .env.$ENV_NAME"
    echo "Also set IMESSAGE_WEBHOOK_SECRET / Mac WEBHOOK_SECRET to the same value, or iMessage auth will diverge."
  fi
  upsert_key "$ENV_FILE" "CONNECTOR_SECRET" "$CONNECTOR_SECRET"
  echo "Wrote CONNECTOR_SECRET into $ENV_FILE"
else
  echo "CONNECTOR_SECRET already set in .env.$ENV_NAME"
fi

PROJECT_REF="$(get_val "$ENV_FILE" "SUPABASE_PROJECT_REF")"
if [[ -z "$PROJECT_REF" ]]; then
  PROJECT_REF="$(get_val "$ENV_FILE" "SUPABASE_PROJECT_ID")"
fi
SERVICE_KEY="$(get_val "$ENV_FILE" "SUPABASE_SECRET_KEY")"
if [[ -z "$SERVICE_KEY" ]]; then
  SERVICE_KEY="$(get_val "$ENV_FILE" "SUPABASE_SERVICE_ROLE_KEY")"
fi

if [[ -z "$PROJECT_REF" || -z "$SERVICE_KEY" ]]; then
  echo "Need SUPABASE_PROJECT_REF (or SUPABASE_PROJECT_ID) and SUPABASE_SECRET_KEY in $ENV_FILE" >&2
  exit 1
fi

SUPABASE_URL="https://${PROJECT_REF}.supabase.co"
CONNECTOR_URL="${SUPABASE_URL}/functions/v1/print-connector"

mkdir -p "$PRINT_BRIDGE_DIR"
cat > "$PRINT_BRIDGE_DIR/.env" <<EOF
# Generated by secrets/scripts/setup-print-bridge-env.sh ($(date -u +%Y-%m-%dT%H:%MZ))
# Env source: secrets/.env.${ENV_NAME}

SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_KEY=${SERVICE_KEY}

CONNECTOR_URL=${CONNECTOR_URL}
CONNECTOR_SECRET=${CONNECTOR_SECRET}
CONNECTOR_ID=altitutor-mac-mini-print

CUPS_QUEUE=FUJ
POLL_INTERVAL_MS=15000
HEARTBEAT_INTERVAL_MS=30000
CLAIM_LIMIT=5
TMP_DIR=/tmp/print-bridge
EOF

# Prefer not to leave world-readable secrets on disk
chmod 600 "$PRINT_BRIDGE_DIR/.env" 2>/dev/null || true

echo ""
echo "Wrote $PRINT_BRIDGE_DIR/.env"
echo "Next:"
echo "  1. cd secrets/scripts && ./deploy-supabase.sh   # pushes CONNECTOR_SECRET (+ IMESSAGE_*) to Edge Functions"
echo "  2. Optional: set CONNECTOR_SECRET in imessage-bridge/.env to the same value (today it falls back to WEBHOOK_SECRET)"
echo "  3. cd $PRINT_BRIDGE_DIR && npm install && npm run build && pm2 start ecosystem.config.js"
echo ""
echo "Auth note: print-connector accepts PRINT_CONNECTOR_SECRET || CONNECTOR_SECRET || IMESSAGE_WEBHOOK_SECRET"
echo "iMessage Mac bridge uses CONNECTOR_SECRET || WEBHOOK_SECRET; Edge uses CONNECTOR_SECRET || IMESSAGE_WEBHOOK_SECRET"
