'use client';
import {useEffect,useState} from 'react';
import {Button,Input,Label} from '@altitutor/ui';
import {StudentPageContainer} from '@/shared/components/layouts';
import {SettingsPageHeader} from '@/features/settings/components/SettingsPageHeader';

export function FlashcardSettingsPage(){const [newLimit,setNewLimit]=useState(20);const [reviewLimit,setReviewLimit]=useState(200);const [timezone,setTimezone]=useState('Australia/Adelaide');const [pending,setPending]=useState<string|null>(null);const [saved,setSaved]=useState(false);
  const [presets,setPresets]=useState<{id:string;name:string;defaultRetention:number;desiredRetention:number|null;optimizedAt:string|null}[]>([]);
  useEffect(()=>{void Promise.all([fetch('/api/flashcards/preferences').then(r=>r.json()),fetch('/api/flashcards/presets').then(r=>r.json())]).then(([preferences,presetResult])=>{const data=preferences.data;setNewLimit(data.new_cards_per_study_day);setReviewLimit(data.review_cards_per_study_day);setTimezone(data.pending_timezone??data.timezone);setPending(data.pending_timezone);setPresets(presetResult.data??[]);});},[]);
  const save=async()=>{const response=await fetch('/api/flashcards/preferences',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({newLimit,reviewLimit,timezone})});if(response.ok){const {data}=await response.json();setPending(data.pending_timezone);setSaved(true);}};
  return <StudentPageContainer className="space-y-6"><SettingsPageHeader title="Flashcard settings" description="Daily study allowances and your 4 am study-day timezone" backHref="/settings" backLabel="All settings"/>
    <div className="max-w-xl space-y-5 rounded-xl border p-6"><div><Label htmlFor="new-limit">New cards per study day</Label><Input id="new-limit" type="number" min={0} max={9999} value={newLimit} onChange={e=>setNewLimit(Number(e.target.value))}/><p className="text-xs text-muted-foreground">Use 9999 for unlimited.</p></div>
    <div><Label htmlFor="review-limit">Reviews per study day</Label><Input id="review-limit" type="number" min={0} max={9999} value={reviewLimit} onChange={e=>setReviewLimit(Number(e.target.value))}/></div>
    <div><Label htmlFor="timezone">Timezone</Label><Input id="timezone" value={timezone} onChange={e=>setTimezone(e.target.value)}/><p className="text-xs text-muted-foreground">Browser suggestion: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Changes take effect at the next 4 am boundary.</p>{pending?<p className="text-xs text-amber-600">Pending: {pending}</p>:null}</div>
    <Button onClick={()=>void save()}>Save settings</Button>{saved?<span className="ml-3 text-sm text-muted-foreground">Saved</span>:null}</div>
    <div className="max-w-xl space-y-4 rounded-xl border p-6"><h2 className="text-lg font-semibold">Desired retention</h2><p className="text-sm text-muted-foreground">Personal per-preset target (0.80–0.95). Higher values schedule more reviews.</p>{presets.map(preset=><div key={preset.id}><Label htmlFor={`retention-${preset.id}`}>{preset.name}</Label><Input id={`retention-${preset.id}`} type="number" min={0.8} max={0.95} step={0.01} value={preset.desiredRetention??preset.defaultRetention} onChange={e=>setPresets(current=>current.map(item=>item.id===preset.id?{...item,desiredRetention:Number(e.target.value)}:item))}/>{preset.optimizedAt?<p className="text-xs text-muted-foreground">Parameters optimised {new Date(preset.optimizedAt).toLocaleDateString()}</p>:null}</div>)}<Button variant="outline" onClick={()=>void Promise.all(presets.map(preset=>fetch('/api/flashcards/presets',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({presetId:preset.id,desiredRetention:preset.desiredRetention??preset.defaultRetention})})))}>Save retention</Button></div>
    </StudentPageContainer>;
}
