-- Replace generic taxonomy copy with student-facing descriptions.
-- The previous description pass intentionally filled gaps from the section/root
-- hierarchy. This pass overwrites those placeholders with explanations of what
-- the tag or category means for students during practice and review.

CREATE OR REPLACE FUNCTION public.__tmp_ucat_taxonomy_description_doc(p_text TEXT)
RETURNS JSONB
LANGUAGE SQL
IMMUTABLE
AS $$
  SELECT jsonb_build_object(
    'type', 'doc',
    'content', jsonb_build_array(
      jsonb_build_object(
        'type', 'paragraph',
        'content', jsonb_build_array(
          jsonb_build_object('type', 'text', 'text', p_text)
        )
      )
    )
  );
$$;

WITH category_descriptions(section_name, category_name, description_text) AS (
  VALUES
    ('Verbal Reasoning', 'Reading Comprehension', 'Four-option Verbal Reasoning questions where you must understand the passage, locate evidence, and choose the option best supported by the text.'),
    ('Verbal Reasoning', 'True, False, Can''t Tell', 'Statement-judgement questions where you decide whether the passage proves the statement true, contradicts it, or does not give enough information.'),
    ('Decision Making', 'Logical Puzzles', 'Constraint-based problems where you track rules, positions, assignments, or selections to work out what must be possible or true.'),
    ('Decision Making', 'Probabilistic and Statistical Reasoning', 'Questions where the main task is using probability, risk, averages, or data summaries rather than everyday intuition.'),
    ('Decision Making', 'Recognising Assumptions', 'Argument questions where you identify which reason, assumption, or objection most strongly supports or weakens a claim.'),
    ('Decision Making', 'Syllogisms', 'Yes/no conclusion questions where the answer depends only on whether the conclusion necessarily follows from the given statements.'),
    ('Decision Making', 'Venn Diagrams', 'Set-membership questions where you organise overlaps, exclusions, and totals using Venn-style regions or equivalent logic.'),
    ('Quantitative Reasoning', 'Data Tables', 'QR stems where the key information is in a table, so success depends on finding the right row, column, unit, and comparison.'),
    ('Quantitative Reasoning', 'Graphs and Charts', 'QR stems where you read values, trends, or proportions from a chart or graph before doing any calculation.'),
    ('Quantitative Reasoning', 'Timetables and Calendars', 'QR stems built around times, dates, schedules, or durations, often requiring careful unit conversion and ordering.'),
    ('Quantitative Reasoning', 'Maps and Diagrams', 'QR stems where a map, plan, layout, or geometric diagram carries information needed for the calculation.'),
    ('Quantitative Reasoning', 'Mixed Data Sources', 'QR stems where you must combine information from more than one source, such as a table plus a chart or short text.'),
    ('Quantitative Reasoning', 'Text-Only Scenarios', 'QR stems where all numbers are embedded in prose, so the first skill is extracting and organising the relevant quantities.'),
    ('Situational Judgement', 'How Appropriate', 'SJ questions asking how good a proposed action is, balancing patient safety, professionalism, honesty, teamwork, and escalation.'),
    ('Situational Judgement', 'How Important', 'SJ questions asking how much a consideration should influence the decision, not whether the action itself is right or wrong.')
)
UPDATE public.question_stem_categories category
SET
  description = public.__tmp_ucat_taxonomy_description_doc(category_descriptions.description_text),
  updated_at = NOW()
FROM category_descriptions
JOIN public.ucat_sections section
  ON section.name = category_descriptions.section_name
WHERE category.ucat_section_id = section.id
  AND category.name = category_descriptions.category_name;

WITH RECURSIVE tag_paths AS (
  SELECT
    tag.id,
    tag.name,
    tag.parent_question_tag_id,
    tag.ucat_section_id,
    section.name AS section_name,
    tag.name::TEXT AS path
  FROM public.question_tags tag
  JOIN public.ucat_sections section
    ON section.id = tag.ucat_section_id
  WHERE tag.parent_question_tag_id IS NULL

  UNION ALL

  SELECT
    child.id,
    child.name,
    child.parent_question_tag_id,
    parent.ucat_section_id,
    parent.section_name,
    parent.path || ' / ' || child.name
  FROM public.question_tags child
  JOIN tag_paths parent
    ON parent.id = child.parent_question_tag_id
),
tag_descriptions(section_name, path, description_text) AS (
  VALUES
    ('Verbal Reasoning', 'Evidence handling', 'Use this for questions where the main skill is finding the right evidence in the passage and using it accurately.'),
    ('Verbal Reasoning', 'Evidence handling / Detail retrieval', 'The answer is based on a stated detail. Practice locating the exact sentence or phrase and checking it against the option.'),
    ('Verbal Reasoning', 'Evidence handling / Paraphrasing', 'The passage and answer say the same idea in different words, so focus on meaning rather than matching exact vocabulary.'),
    ('Verbal Reasoning', 'Evidence handling / Inference', 'You need to draw a careful conclusion from what the passage implies without adding outside knowledge or assumptions.'),
    ('Verbal Reasoning', 'Evidence handling / Insufficient information / Can''t tell', 'The passage does not provide enough evidence to prove or disprove the statement, even if it sounds plausible.'),
    ('Verbal Reasoning', 'Evidence handling / Word or phrase reference', 'You must work out what a word, phrase, pronoun, or quoted expression refers to in its local context.'),
    ('Verbal Reasoning', 'Evidence handling / Cross-paragraph evidence', 'The answer depends on combining information from more than one part of the passage, not just one sentence.'),
    ('Verbal Reasoning', 'Author and passage meaning', 'Use this for questions about the overall meaning, purpose, viewpoint, or argument of the passage.'),
    ('Verbal Reasoning', 'Author and passage meaning / Main idea / summary', 'You need to identify the central point or best summary, avoiding options that only capture a minor detail.'),
    ('Verbal Reasoning', 'Author and passage meaning / Author purpose or attitude', 'The question asks why the author included something or what tone, stance, or attitude the author takes.'),
    ('Verbal Reasoning', 'Author and passage meaning / Opinion vs fact', 'You need to separate factual claims from judgements, interpretations, or viewpoints in the passage.'),
    ('Verbal Reasoning', 'Author and passage meaning / Argument support', 'You are judging which statement best supports, weakens, or follows from an argument made in the passage.'),
    ('Verbal Reasoning', 'Question wording traps', 'Use this for questions where the wording changes the task and can easily lead to a misread answer.'),
    ('Verbal Reasoning', 'Question wording traps / Qualifiers', 'Words such as some, most, always, only, usually, or except change how strong a statement is.'),
    ('Verbal Reasoning', 'Question wording traps / Negatives', 'The question or option uses not, never, except, least, or a similar reversal, so check what is being excluded.'),
    ('Verbal Reasoning', 'Question wording traps / Long statement', 'Long options need to be checked clause by clause because one inaccurate part can make the whole statement wrong.'),
    ('Verbal Reasoning', 'Question wording traps / No clear keyword', 'There is no obvious search term, so you need to locate the relevant idea rather than scanning for a single word.'),
    ('Verbal Reasoning', 'Application', 'Use this when a passage idea has to be applied to a new situation, example, or changed piece of information.'),
    ('Verbal Reasoning', 'Application / New information', 'The question introduces a new fact and asks how it affects what can be concluded from the passage.'),
    ('Verbal Reasoning', 'Application / Hypothetical application', 'You apply the passage to a what-if scenario while keeping the hypothetical separate from the original text.'),

    ('Decision Making', 'Deductive logic', 'Use this for formal reasoning where the task is deciding what must follow from the stated information.'),
    ('Decision Making', 'Deductive logic / Quantifiers: all / some / none', 'Track exactly what all, some, none, not all, or only allow you to conclude.'),
    ('Decision Making', 'Deductive logic / Conditional reasoning', 'Work with if, only if, unless, and other rule statements without reversing or overextending them.'),
    ('Decision Making', 'Deductive logic / Negation and complements', 'Notice what is excluded, denied, or left outside a set so you do not treat opposites as equivalent.'),
    ('Decision Making', 'Deductive logic / Must be true / necessarily follows', 'Choose conclusions guaranteed by the information, not conclusions that merely sound likely.'),
    ('Decision Making', 'Deductive logic / Cannot be concluded', 'Identify statements that are not proven by the information, even when they fit common sense.'),
    ('Decision Making', 'Rule-based problem solving', 'Use this for puzzles where you must apply several rules systematically to narrow the possible arrangements.'),
    ('Decision Making', 'Rule-based problem solving / Ordering and ranking', 'The problem involves positions, order, relative rank, before-after rules, or highest-lowest comparisons.'),
    ('Decision Making', 'Rule-based problem solving / Matching and assignment', 'You need to match people, objects, groups, or features while satisfying all given constraints.'),
    ('Decision Making', 'Rule-based problem solving / Seating or spatial arrangement', 'The rules describe locations, neighbours, directions, or layout relationships that must be mapped carefully.'),
    ('Decision Making', 'Rule-based problem solving / Scheduling and selection', 'You decide which times, events, or options can be chosen while respecting availability or selection rules.'),
    ('Decision Making', 'Rule-based problem solving / Multi-constraint deduction', 'Several constraints interact, so the solution requires combining rules rather than using one clue in isolation.'),
    ('Decision Making', 'Set and Venn reasoning', 'Use this for membership, overlap, and exclusion problems that can be represented with sets or Venn regions.'),
    ('Decision Making', 'Set and Venn reasoning / Diagram selection', 'You must choose or build the diagram that correctly represents the stated relationships.'),
    ('Decision Making', 'Set and Venn reasoning / Region counting', 'The question asks for counts in specific Venn regions, often after accounting for overlaps.'),
    ('Decision Making', 'Set and Venn reasoning / Intersections and unions', 'The key move is distinguishing overlap from either-or membership across one or more groups.'),
    ('Decision Making', 'Set and Venn reasoning / Only / neither / complements', 'Pay close attention to people or items in only one group, in neither group, or outside a described set.'),
    ('Decision Making', 'Set and Venn reasoning / Three-plus sets', 'The problem involves three or more groups, so pairwise overlaps and total overlaps must be kept separate.'),
    ('Decision Making', 'Probability and data reasoning', 'Use this where the answer depends on probability, risk, data summaries, or numerical evidence.'),
    ('Decision Making', 'Probability and data reasoning / Basic probability', 'Calculate chance from favourable outcomes and total outcomes, keeping the denominator clear.'),
    ('Decision Making', 'Probability and data reasoning / Conditional probability', 'The probability changes because you are told an extra condition or limited to a subgroup.'),
    ('Decision Making', 'Probability and data reasoning / Without replacement / combinations', 'Outcomes change after each selection or require counting combinations rather than treating events as independent.'),
    ('Decision Making', 'Probability and data reasoning / Expected value or risk comparison', 'Compare options by expected outcome, risk level, or long-run value rather than surface appeal.'),
    ('Decision Making', 'Probability and data reasoning / Table interpretation', 'Read the relevant rows and columns accurately before drawing a conclusion from the data.'),
    ('Decision Making', 'Probability and data reasoning / Fraction / percentage comparison', 'Convert or compare fractions and percentages so the evidence is judged on the same scale.'),
    ('Decision Making', 'Argument evaluation', 'Use this for questions about whether a reason genuinely supports a conclusion or proposed action.'),
    ('Decision Making', 'Argument evaluation / Strongest argument', 'Choose the argument that is most relevant, evidence-based, and directly connected to the claim.'),
    ('Decision Making', 'Argument evaluation / Causal assumption', 'Spot when an argument depends on an unstated cause-and-effect link.'),
    ('Decision Making', 'Argument evaluation / Relevance and scope', 'Avoid options that are true but outside the issue, population, timeframe, or decision being considered.'),
    ('Decision Making', 'Argument evaluation / Evidence strength', 'Judge whether the evidence is direct, reliable, and sufficient rather than anecdotal or weakly connected.'),
    ('Decision Making', 'Argument evaluation / Practical feasibility', 'Assess whether a proposed action can realistically be carried out with the stated resources or constraints.'),
    ('Decision Making', 'Argument evaluation / Policy or public benefit', 'The argument turns on wider outcomes such as fairness, public safety, cost, or benefit to a group.'),
    ('Decision Making', 'Decision wording traps', 'Use this when precise wording controls the answer, especially in questions asking what is allowed, excluded, or sufficient.'),
    ('Decision Making', 'Decision wording traps / Considering only stated factors', 'Base the answer only on the listed information, not on real-world assumptions or extra possibilities.'),
    ('Decision Making', 'Decision wording traps / Yes/no sufficiency', 'Decide whether the information is enough to answer yes or no, rather than solving beyond what is asked.'),
    ('Decision Making', 'Decision wording traps / False statement', 'The task is to find the statement that is false, contradicted, or not supported by the information.'),
    ('Decision Making', 'Decision wording traps / Greater than / less than comparison', 'Small wording differences in more than, less than, at least, or at most determine the correct comparison.'),

    ('Quantitative Reasoning', 'Arithmetic', 'Use this for core number operations and calculator habits that underpin most QR questions.'),
    ('Quantitative Reasoning', 'Arithmetic / Addition', 'Combine quantities, totals, or increases accurately, especially when several values must be added.'),
    ('Quantitative Reasoning', 'Arithmetic / Subtraction', 'Find differences, remaining amounts, decreases, or gaps between two values.'),
    ('Quantitative Reasoning', 'Arithmetic / Multiplication', 'Scale a quantity, find repeated groups, or calculate totals from equal-sized units.'),
    ('Quantitative Reasoning', 'Arithmetic / Division', 'Share a total, calculate a per-unit value, or split one quantity by another.'),
    ('Quantitative Reasoning', 'Arithmetic / Mental maths', 'Use efficient number sense to simplify calculations or check calculator results under time pressure.'),
    ('Quantitative Reasoning', 'Arithmetic / Estimation', 'Approximate values to judge the size of an answer, eliminate options, or detect a calculation error.'),
    ('Quantitative Reasoning', 'Arithmetic / Rounding', 'Round values to a stated precision or decide how rounding affects the final answer.'),
    ('Quantitative Reasoning', 'Arithmetic / Order of operations (BEDMAS)', 'Apply brackets, powers, division, multiplication, addition, and subtraction in the correct order.'),
    ('Quantitative Reasoning', 'Fractions', 'Use this for questions where parts of a whole, fraction operations, or fraction conversions are central.'),
    ('Quantitative Reasoning', 'Fractions / Simplifying fractions', 'Reduce fractions to an equivalent simpler form by dividing numerator and denominator by common factors.'),
    ('Quantitative Reasoning', 'Fractions / Equivalent fractions', 'Recognise or create fractions with the same value despite different numerators and denominators.'),
    ('Quantitative Reasoning', 'Fractions / Adding fractions', 'Add fractions by using common denominators or converting to an easier equivalent form.'),
    ('Quantitative Reasoning', 'Fractions / Subtracting fractions', 'Subtract fractions carefully after aligning denominators and keeping track of the remaining part.'),
    ('Quantitative Reasoning', 'Fractions / Multiplying fractions', 'Multiply fractional parts, often to find a fraction of another fraction or quantity.'),
    ('Quantitative Reasoning', 'Fractions / Dividing fractions', 'Divide by a fraction by using the reciprocal or an equivalent ratio method.'),
    ('Quantitative Reasoning', 'Fractions / Converting fractions to decimals', 'Turn a fraction into a decimal so it can be compared or used in a calculation.'),
    ('Quantitative Reasoning', 'Fractions / Converting fractions to percentages', 'Convert fractional parts into percentages to compare proportions on a common scale.'),
    ('Quantitative Reasoning', 'Decimals', 'Use this for calculations where place value and decimal precision affect the answer.'),
    ('Quantitative Reasoning', 'Decimals / Addition/subtraction', 'Line up decimal places when adding or subtracting values with decimal points.'),
    ('Quantitative Reasoning', 'Decimals / Multiplication', 'Multiply decimal values while keeping track of decimal places and scale.'),
    ('Quantitative Reasoning', 'Decimals / Division', 'Divide decimal values and interpret remainders or recurring decimals appropriately.'),
    ('Quantitative Reasoning', 'Decimals / Decimal place conversions', 'Move between tenths, hundredths, thousandths, and powers of ten without changing the value incorrectly.'),
    ('Quantitative Reasoning', 'Decimals / Rounding', 'Round decimal answers to a required number of decimal places or significant figures.'),
    ('Quantitative Reasoning', 'Percentages', 'Use this when the question is about proportions out of 100, percentage change, or reverse percentage reasoning.'),
    ('Quantitative Reasoning', 'Percentages / Finding a percentage of a quantity', 'Calculate part of a quantity by applying a given percentage.'),
    ('Quantitative Reasoning', 'Percentages / Percentage increase', 'Increase a starting value by a stated percentage and find the new value or increase amount.'),
    ('Quantitative Reasoning', 'Percentages / Percentage decrease', 'Decrease a starting value by a stated percentage and find the new value or decrease amount.'),
    ('Quantitative Reasoning', 'Percentages / Reverse percentages', 'Work backwards from a final value to find the original value before a percentage change.'),
    ('Quantitative Reasoning', 'Percentages / Percentage change', 'Find the percentage increase or decrease between two values.'),
    ('Quantitative Reasoning', 'Percentages / Percentage difference', 'Compare two quantities as a percentage of a reference value.'),
    ('Quantitative Reasoning', 'Percentages / Compound percentage change', 'Apply repeated percentage changes where each change acts on the updated value.'),
    ('Quantitative Reasoning', 'Ratios', 'Use this where quantities are compared or shared according to relative parts.'),
    ('Quantitative Reasoning', 'Ratios / Simplifying ratios', 'Reduce a ratio to its simplest equivalent form by dividing all parts by a common factor.'),
    ('Quantitative Reasoning', 'Ratios / Sharing amounts in a ratio', 'Split a total into parts according to a given ratio.'),
    ('Quantitative Reasoning', 'Ratios / Ratio interpretation', 'Translate a ratio into actual quantities, proportions, or relationships in the scenario.'),
    ('Quantitative Reasoning', 'Ratios / Comparing ratios', 'Put ratios onto a common basis so you can tell which relationship is larger or smaller.'),
    ('Quantitative Reasoning', 'Proportion', 'Use this for scaling relationships where quantities change together.'),
    ('Quantitative Reasoning', 'Proportion / Direct proportion', 'As one quantity increases, the other increases by the same factor.'),
    ('Quantitative Reasoning', 'Proportion / Inverse proportion', 'As one quantity increases, the other decreases in a linked way, such as more workers taking less time.'),
    ('Quantitative Reasoning', 'Proportion / Scaling', 'Scale values up or down using a consistent multiplier.'),
    ('Quantitative Reasoning', 'Speed - Distance - Time', 'Use the relationship between speed, distance, and time, including rates and unit conversions.'),
    ('Quantitative Reasoning', 'Unit Conversions', 'Use this when converting between units is necessary before the calculation makes sense.'),
    ('Quantitative Reasoning', 'Unit Conversions / Length', 'Convert or compare distances and lengths such as millimetres, centimetres, metres, and kilometres.'),
    ('Quantitative Reasoning', 'Unit Conversions / Length / mm', 'Work with millimetres, usually by converting to or from centimetres or metres.'),
    ('Quantitative Reasoning', 'Unit Conversions / Length / cm', 'Work with centimetres, often converting to millimetres or metres.'),
    ('Quantitative Reasoning', 'Unit Conversions / Length / m', 'Work with metres and convert them to smaller or larger length units when needed.'),
    ('Quantitative Reasoning', 'Unit Conversions / Length / km', 'Work with kilometres, commonly converting to metres or using them in speed calculations.'),
    ('Quantitative Reasoning', 'Unit Conversions / Weight', 'Convert or compare masses such as milligrams, grams, kilograms, and tonnes.'),
    ('Quantitative Reasoning', 'Unit Conversions / Weight / mg', 'Work with milligrams, especially in small-dose or fine-measurement contexts.'),
    ('Quantitative Reasoning', 'Unit Conversions / Weight / g', 'Work with grams and convert them to milligrams or kilograms.'),
    ('Quantitative Reasoning', 'Unit Conversions / Weight / kg', 'Work with kilograms and convert them to grams or tonnes where appropriate.'),
    ('Quantitative Reasoning', 'Unit Conversions / Weight / Tonnes', 'Work with tonnes and convert to kilograms for comparison or calculation.'),
    ('Quantitative Reasoning', 'Unit Conversions / Volume', 'Convert or compare capacities such as millilitres and litres.'),
    ('Quantitative Reasoning', 'Unit Conversions / Volume / mL', 'Work with millilitres, usually converting to or from litres.'),
    ('Quantitative Reasoning', 'Unit Conversions / Volume / L', 'Work with litres and convert to millilitres when smaller units are needed.'),
    ('Quantitative Reasoning', 'Unit Conversions / Time', 'Convert between time units before comparing, scheduling, or calculating rates.'),
    ('Quantitative Reasoning', 'Unit Conversions / Time / seconds', 'Use seconds accurately, often converting to minutes or hours.'),
    ('Quantitative Reasoning', 'Unit Conversions / Time / minutes', 'Use minutes accurately, often converting to hours or seconds.'),
    ('Quantitative Reasoning', 'Unit Conversions / Time / hours', 'Use hours accurately, especially in rates, journeys, or schedules.'),
    ('Quantitative Reasoning', 'Unit Conversions / Time / days', 'Use days accurately, often converting to hours or weeks in longer schedules.'),
    ('Quantitative Reasoning', 'Unit Conversions / Currency', 'Convert or compare money values, including exchange rates and foreign currencies.'),
    ('Quantitative Reasoning', 'Unit Conversions / Currency / Exchange rates', 'Apply exchange rates in the correct direction and account for fees or commissions if given.'),
    ('Quantitative Reasoning', 'Unit Conversions / Currency / Foreign currencies', 'Compare or convert values across currencies without mixing units.'),
    ('Quantitative Reasoning', 'Averages', 'Use this for summary measures that describe a set of values.'),
    ('Quantitative Reasoning', 'Averages / Mean', 'Find or use the arithmetic average, often by total divided by number of values.'),
    ('Quantitative Reasoning', 'Averages / Median', 'Find the middle value after ordering the data.'),
    ('Quantitative Reasoning', 'Averages / Mode', 'Find the value or category that appears most often.'),
    ('Quantitative Reasoning', 'Averages / Range', 'Find the spread by subtracting the smallest value from the largest.'),
    ('Quantitative Reasoning', 'Basic Statistics', 'Use this for reading and comparing datasets, summaries, and trends.'),
    ('Quantitative Reasoning', 'Basic Statistics / Comparing datasets', 'Compare two or more groups using relevant totals, averages, spreads, or proportions.'),
    ('Quantitative Reasoning', 'Basic Statistics / Reading summary statistics', 'Interpret summary values such as mean, median, range, totals, or percentages.'),
    ('Quantitative Reasoning', 'Basic Statistics / Interpreting trends', 'Identify increases, decreases, patterns, or changes over time from the data.'),
    ('Quantitative Reasoning', 'Basic Statistics / Comparing means', 'Compare averages fairly, including checking whether the underlying groups differ in size.'),
    ('Quantitative Reasoning', 'Basic Statistics / Comparing percentages', 'Compare proportions on a common percentage scale rather than raw counts alone.'),
    ('Quantitative Reasoning', 'Tables and Financial Maths', 'Use this for financial scenarios involving prices, costs, revenue, tax, interest, or table lookups.'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Profit', 'Calculate gain after costs are subtracted from revenue or selling price.'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Loss', 'Calculate how much money is lost when costs exceed revenue or selling price.'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Mark-up', 'Increase a cost price by a percentage or amount to find a selling price.'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Margin', 'Express profit as a proportion of selling price or revenue.'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Discounts', 'Reduce a price by a stated amount or percentage and find the sale price.'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / VAT/GST', 'Add or remove tax from a price and distinguish tax-inclusive from tax-exclusive amounts.'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Interest', 'Use interest rules to calculate growth of money over time.'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Interest / Simple interest', 'Calculate interest only on the original principal.'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Interest / Compound interest', 'Calculate interest on an amount that grows after each interest period.'),
    ('Quantitative Reasoning', 'Algebra', 'Use symbols, unknowns, or equations to represent relationships before solving for a value.'),
    ('Quantitative Reasoning', 'Probability', 'Use this when the answer depends on chance, expected outcomes, or likelihood.'),
    ('Quantitative Reasoning', 'Probability / Simple probability', 'Find the chance of an event from favourable outcomes over total possible outcomes.'),
    ('Quantitative Reasoning', 'Probability / Expected outcomes', 'Use probability to estimate the number of times an event should occur over repeated trials.'),
    ('Quantitative Reasoning', 'Geometry', 'Use this when shapes, dimensions, or spatial measurements drive the calculation.'),
    ('Quantitative Reasoning', 'Geometry / Area', 'Calculate the amount of surface inside a two-dimensional shape.'),
    ('Quantitative Reasoning', 'Geometry / Area / Rectangle', 'Use rectangle area relationships, usually length times width.'),
    ('Quantitative Reasoning', 'Geometry / Area / Square', 'Use square area relationships where all sides are equal.'),
    ('Quantitative Reasoning', 'Geometry / Area / Triangle', 'Use triangle area relationships, usually half times base times height.'),
    ('Quantitative Reasoning', 'Geometry / Perimeter', 'Calculate the total distance around the outside of a shape.'),
    ('Quantitative Reasoning', 'Geometry / Volume', 'Calculate the space inside a three-dimensional object.'),
    ('Quantitative Reasoning', 'Geometry / Volume / Cubes', 'Use cube volume relationships where all edges are equal.'),
    ('Quantitative Reasoning', 'Geometry / Volume / Rectangular prisms', 'Use length, width, and height to calculate the volume of a rectangular prism.'),
    ('Quantitative Reasoning', 'Geometry / Circumference', 'Calculate or use the distance around a circle.'),
    ('Quantitative Reasoning', 'Time Calculations', 'Use this for schedules, elapsed time, time zones, or calendar-based reasoning.'),
    ('Quantitative Reasoning', 'Time Calculations / Timetables', 'Read departure, arrival, or event times from a timetable and compare them correctly.'),
    ('Quantitative Reasoning', 'Time Calculations / Scheduling', 'Arrange or choose times while respecting durations, availability, or order.'),
    ('Quantitative Reasoning', 'Time Calculations / Duration', 'Find elapsed time between two points, including across hours, days, or date boundaries.'),
    ('Quantitative Reasoning', 'Time Calculations / Time zones', 'Convert times between places while accounting for time-zone differences.'),
    ('Quantitative Reasoning', 'Multi-Step Calculations', 'Use this when the answer requires several linked calculations and intermediate results must be carried forward.'),

    ('Situational Judgement', 'Patient welfare and safety', 'Use this for scenarios where protecting patients from harm is the main priority.'),
    ('Situational Judgement', 'Patient welfare and safety / Patient safety', 'The best response reduces risk to the patient or prevents unsafe care.'),
    ('Situational Judgement', 'Patient welfare and safety / Infection risk', 'The scenario involves preventing infection spread through hygiene, isolation, or safe clinical practice.'),
    ('Situational Judgement', 'Patient welfare and safety / Scope of competence', 'You must recognise when someone should not act beyond their training, role, or supervision level.'),
    ('Situational Judgement', 'Patient welfare and safety / Escalating concerns', 'The appropriate action is to raise a risk or concern with someone able to act on it.'),
    ('Situational Judgement', 'Professional conduct', 'Use this for behaviour expected of medical students and doctors, especially trust, honesty, respect, and responsibility.'),
    ('Situational Judgement', 'Professional conduct / Professionalism', 'The scenario tests whether behaviour meets expected professional standards, even under pressure.'),
    ('Situational Judgement', 'Professional conduct / Honesty and accountability', 'The best response involves being truthful, admitting errors, and taking responsibility for next steps.'),
    ('Situational Judgement', 'Professional conduct / Confidentiality', 'You must protect patient information and share it only with appropriate people for appropriate reasons.'),
    ('Situational Judgement', 'Professional conduct / Respect and dignity', 'The response should treat patients, colleagues, and others with courtesy, fairness, and sensitivity.'),
    ('Situational Judgement', 'Professional conduct / Following protocol', 'The scenario turns on using established procedures rather than improvising or ignoring rules.'),
    ('Situational Judgement', 'Teamwork and communication', 'Use this where good outcomes depend on clear communication, collaboration, and appropriate support.'),
    ('Situational Judgement', 'Teamwork and communication / Speaking up', 'You should raise a concern clearly and constructively rather than staying silent.'),
    ('Situational Judgement', 'Teamwork and communication / Peer concern', 'The scenario involves noticing a peer may be struggling, unsafe, dishonest, or in need of support.'),
    ('Situational Judgement', 'Teamwork and communication / Conflict with colleague', 'The task is to handle disagreement or poor behaviour professionally without escalating unnecessarily.'),
    ('Situational Judgement', 'Teamwork and communication / Seeking senior support', 'The best response is to involve a supervisor or senior when the issue is beyond your role or risk level.'),
    ('Situational Judgement', 'Teamwork and communication / Patient interaction', 'The scenario tests communication with a patient, including listening, empathy, explanation, and boundaries.'),
    ('Situational Judgement', 'Personal judgement', 'Use this for situations where personal pressures must be balanced against professional responsibility.'),
    ('Situational Judgement', 'Personal judgement / Workload and prioritisation', 'You must prioritise tasks or commitments without compromising patient care or professional duties.'),
    ('Situational Judgement', 'Personal judgement / Wellbeing and mental health', 'The scenario involves recognising distress, burnout, or impairment and seeking appropriate support.'),
    ('Situational Judgement', 'Personal judgement / Managing commitments', 'The challenge is handling competing responsibilities honestly and planning ahead.'),
    ('Situational Judgement', 'Personal judgement / Career opportunity vs responsibility', 'You must balance personal advancement with duties to patients, colleagues, or the team.'),
    ('Situational Judgement', 'Personal judgement / Peer pressure', 'The scenario tests whether you can resist pressure from others when it conflicts with professional standards.'),
    ('Situational Judgement', 'Ethical principles', 'Use this where a core medical ethics principle explains why one response is better than another.'),
    ('Situational Judgement', 'Ethical principles / Beneficence', 'The response promotes the patient''s welfare or helps achieve a good outcome.'),
    ('Situational Judgement', 'Ethical principles / Non-maleficence', 'The response avoids causing harm or reduces the risk of harm.'),
    ('Situational Judgement', 'Ethical principles / Autonomy', 'The response respects the patient''s right to make informed choices about their care.'),
    ('Situational Judgement', 'Ethical principles / Justice', 'The response treats people fairly and uses time, attention, or resources appropriately.'),
    ('Situational Judgement', 'Ethical principles / Consent', 'The scenario turns on valid permission, informed decision-making, or respecting refusal.'),
    ('Situational Judgement', 'Ethical principles / Confidentiality', 'The ethical issue is protecting private information while recognising when disclosure is justified.')
)
UPDATE public.question_tags tag
SET
  description = public.__tmp_ucat_taxonomy_description_doc(tag_descriptions.description_text),
  updated_at = NOW()
FROM tag_paths
JOIN tag_descriptions
  ON tag_descriptions.section_name = tag_paths.section_name
  AND tag_descriptions.path = tag_paths.path
WHERE tag.id = tag_paths.id;

WITH RECURSIVE tag_paths AS (
  SELECT
    tag.id,
    tag.name,
    tag.parent_question_tag_id,
    tag.ucat_section_id,
    section.name AS section_name,
    tag.name::TEXT AS path
  FROM public.question_tags tag
  JOIN public.ucat_sections section
    ON section.id = tag.ucat_section_id
  WHERE tag.parent_question_tag_id IS NULL

  UNION ALL

  SELECT
    child.id,
    child.name,
    child.parent_question_tag_id,
    parent.ucat_section_id,
    parent.section_name,
    parent.path || ' / ' || child.name
  FROM public.question_tags child
  JOIN tag_paths parent
    ON parent.id = child.parent_question_tag_id
),
described_paths(section_name, path) AS (
  VALUES
    ('Verbal Reasoning', 'Evidence handling'),
    ('Verbal Reasoning', 'Evidence handling / Detail retrieval'),
    ('Verbal Reasoning', 'Evidence handling / Paraphrasing'),
    ('Verbal Reasoning', 'Evidence handling / Inference'),
    ('Verbal Reasoning', 'Evidence handling / Insufficient information / Can''t tell'),
    ('Verbal Reasoning', 'Evidence handling / Word or phrase reference'),
    ('Verbal Reasoning', 'Evidence handling / Cross-paragraph evidence'),
    ('Verbal Reasoning', 'Author and passage meaning'),
    ('Verbal Reasoning', 'Author and passage meaning / Main idea / summary'),
    ('Verbal Reasoning', 'Author and passage meaning / Author purpose or attitude'),
    ('Verbal Reasoning', 'Author and passage meaning / Opinion vs fact'),
    ('Verbal Reasoning', 'Author and passage meaning / Argument support'),
    ('Verbal Reasoning', 'Question wording traps'),
    ('Verbal Reasoning', 'Question wording traps / Qualifiers'),
    ('Verbal Reasoning', 'Question wording traps / Negatives'),
    ('Verbal Reasoning', 'Question wording traps / Long statement'),
    ('Verbal Reasoning', 'Question wording traps / No clear keyword'),
    ('Verbal Reasoning', 'Application'),
    ('Verbal Reasoning', 'Application / New information'),
    ('Verbal Reasoning', 'Application / Hypothetical application'),
    ('Decision Making', 'Deductive logic'),
    ('Decision Making', 'Deductive logic / Quantifiers: all / some / none'),
    ('Decision Making', 'Deductive logic / Conditional reasoning'),
    ('Decision Making', 'Deductive logic / Negation and complements'),
    ('Decision Making', 'Deductive logic / Must be true / necessarily follows'),
    ('Decision Making', 'Deductive logic / Cannot be concluded'),
    ('Decision Making', 'Rule-based problem solving'),
    ('Decision Making', 'Rule-based problem solving / Ordering and ranking'),
    ('Decision Making', 'Rule-based problem solving / Matching and assignment'),
    ('Decision Making', 'Rule-based problem solving / Seating or spatial arrangement'),
    ('Decision Making', 'Rule-based problem solving / Scheduling and selection'),
    ('Decision Making', 'Rule-based problem solving / Multi-constraint deduction'),
    ('Decision Making', 'Set and Venn reasoning'),
    ('Decision Making', 'Set and Venn reasoning / Diagram selection'),
    ('Decision Making', 'Set and Venn reasoning / Region counting'),
    ('Decision Making', 'Set and Venn reasoning / Intersections and unions'),
    ('Decision Making', 'Set and Venn reasoning / Only / neither / complements'),
    ('Decision Making', 'Set and Venn reasoning / Three-plus sets'),
    ('Decision Making', 'Probability and data reasoning'),
    ('Decision Making', 'Probability and data reasoning / Basic probability'),
    ('Decision Making', 'Probability and data reasoning / Conditional probability'),
    ('Decision Making', 'Probability and data reasoning / Without replacement / combinations'),
    ('Decision Making', 'Probability and data reasoning / Expected value or risk comparison'),
    ('Decision Making', 'Probability and data reasoning / Table interpretation'),
    ('Decision Making', 'Probability and data reasoning / Fraction / percentage comparison'),
    ('Decision Making', 'Argument evaluation'),
    ('Decision Making', 'Argument evaluation / Strongest argument'),
    ('Decision Making', 'Argument evaluation / Causal assumption'),
    ('Decision Making', 'Argument evaluation / Relevance and scope'),
    ('Decision Making', 'Argument evaluation / Evidence strength'),
    ('Decision Making', 'Argument evaluation / Practical feasibility'),
    ('Decision Making', 'Argument evaluation / Policy or public benefit'),
    ('Decision Making', 'Decision wording traps'),
    ('Decision Making', 'Decision wording traps / Considering only stated factors'),
    ('Decision Making', 'Decision wording traps / Yes/no sufficiency'),
    ('Decision Making', 'Decision wording traps / False statement'),
    ('Decision Making', 'Decision wording traps / Greater than / less than comparison'),
    ('Quantitative Reasoning', 'Arithmetic'),
    ('Quantitative Reasoning', 'Arithmetic / Addition'),
    ('Quantitative Reasoning', 'Arithmetic / Subtraction'),
    ('Quantitative Reasoning', 'Arithmetic / Multiplication'),
    ('Quantitative Reasoning', 'Arithmetic / Division'),
    ('Quantitative Reasoning', 'Arithmetic / Mental maths'),
    ('Quantitative Reasoning', 'Arithmetic / Estimation'),
    ('Quantitative Reasoning', 'Arithmetic / Rounding'),
    ('Quantitative Reasoning', 'Arithmetic / Order of operations (BEDMAS)'),
    ('Quantitative Reasoning', 'Fractions'),
    ('Quantitative Reasoning', 'Fractions / Simplifying fractions'),
    ('Quantitative Reasoning', 'Fractions / Equivalent fractions'),
    ('Quantitative Reasoning', 'Fractions / Adding fractions'),
    ('Quantitative Reasoning', 'Fractions / Subtracting fractions'),
    ('Quantitative Reasoning', 'Fractions / Multiplying fractions'),
    ('Quantitative Reasoning', 'Fractions / Dividing fractions'),
    ('Quantitative Reasoning', 'Fractions / Converting fractions to decimals'),
    ('Quantitative Reasoning', 'Fractions / Converting fractions to percentages'),
    ('Quantitative Reasoning', 'Decimals'),
    ('Quantitative Reasoning', 'Decimals / Addition/subtraction'),
    ('Quantitative Reasoning', 'Decimals / Multiplication'),
    ('Quantitative Reasoning', 'Decimals / Division'),
    ('Quantitative Reasoning', 'Decimals / Decimal place conversions'),
    ('Quantitative Reasoning', 'Decimals / Rounding'),
    ('Quantitative Reasoning', 'Percentages'),
    ('Quantitative Reasoning', 'Percentages / Finding a percentage of a quantity'),
    ('Quantitative Reasoning', 'Percentages / Percentage increase'),
    ('Quantitative Reasoning', 'Percentages / Percentage decrease'),
    ('Quantitative Reasoning', 'Percentages / Reverse percentages'),
    ('Quantitative Reasoning', 'Percentages / Percentage change'),
    ('Quantitative Reasoning', 'Percentages / Percentage difference'),
    ('Quantitative Reasoning', 'Percentages / Compound percentage change'),
    ('Quantitative Reasoning', 'Ratios'),
    ('Quantitative Reasoning', 'Ratios / Simplifying ratios'),
    ('Quantitative Reasoning', 'Ratios / Sharing amounts in a ratio'),
    ('Quantitative Reasoning', 'Ratios / Ratio interpretation'),
    ('Quantitative Reasoning', 'Ratios / Comparing ratios'),
    ('Quantitative Reasoning', 'Proportion'),
    ('Quantitative Reasoning', 'Proportion / Direct proportion'),
    ('Quantitative Reasoning', 'Proportion / Inverse proportion'),
    ('Quantitative Reasoning', 'Proportion / Scaling'),
    ('Quantitative Reasoning', 'Speed - Distance - Time'),
    ('Quantitative Reasoning', 'Unit Conversions'),
    ('Quantitative Reasoning', 'Unit Conversions / Length'),
    ('Quantitative Reasoning', 'Unit Conversions / Length / mm'),
    ('Quantitative Reasoning', 'Unit Conversions / Length / cm'),
    ('Quantitative Reasoning', 'Unit Conversions / Length / m'),
    ('Quantitative Reasoning', 'Unit Conversions / Length / km'),
    ('Quantitative Reasoning', 'Unit Conversions / Weight'),
    ('Quantitative Reasoning', 'Unit Conversions / Weight / mg'),
    ('Quantitative Reasoning', 'Unit Conversions / Weight / g'),
    ('Quantitative Reasoning', 'Unit Conversions / Weight / kg'),
    ('Quantitative Reasoning', 'Unit Conversions / Weight / Tonnes'),
    ('Quantitative Reasoning', 'Unit Conversions / Volume'),
    ('Quantitative Reasoning', 'Unit Conversions / Volume / mL'),
    ('Quantitative Reasoning', 'Unit Conversions / Volume / L'),
    ('Quantitative Reasoning', 'Unit Conversions / Time'),
    ('Quantitative Reasoning', 'Unit Conversions / Time / seconds'),
    ('Quantitative Reasoning', 'Unit Conversions / Time / minutes'),
    ('Quantitative Reasoning', 'Unit Conversions / Time / hours'),
    ('Quantitative Reasoning', 'Unit Conversions / Time / days'),
    ('Quantitative Reasoning', 'Unit Conversions / Currency'),
    ('Quantitative Reasoning', 'Unit Conversions / Currency / Exchange rates'),
    ('Quantitative Reasoning', 'Unit Conversions / Currency / Foreign currencies'),
    ('Quantitative Reasoning', 'Averages'),
    ('Quantitative Reasoning', 'Averages / Mean'),
    ('Quantitative Reasoning', 'Averages / Median'),
    ('Quantitative Reasoning', 'Averages / Mode'),
    ('Quantitative Reasoning', 'Averages / Range'),
    ('Quantitative Reasoning', 'Basic Statistics'),
    ('Quantitative Reasoning', 'Basic Statistics / Comparing datasets'),
    ('Quantitative Reasoning', 'Basic Statistics / Reading summary statistics'),
    ('Quantitative Reasoning', 'Basic Statistics / Interpreting trends'),
    ('Quantitative Reasoning', 'Basic Statistics / Comparing means'),
    ('Quantitative Reasoning', 'Basic Statistics / Comparing percentages'),
    ('Quantitative Reasoning', 'Tables and Financial Maths'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Profit'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Loss'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Mark-up'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Margin'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Discounts'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / VAT/GST'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Interest'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Interest / Simple interest'),
    ('Quantitative Reasoning', 'Tables and Financial Maths / Interest / Compound interest'),
    ('Quantitative Reasoning', 'Algebra'),
    ('Quantitative Reasoning', 'Probability'),
    ('Quantitative Reasoning', 'Probability / Simple probability'),
    ('Quantitative Reasoning', 'Probability / Expected outcomes'),
    ('Quantitative Reasoning', 'Geometry'),
    ('Quantitative Reasoning', 'Geometry / Area'),
    ('Quantitative Reasoning', 'Geometry / Area / Rectangle'),
    ('Quantitative Reasoning', 'Geometry / Area / Square'),
    ('Quantitative Reasoning', 'Geometry / Area / Triangle'),
    ('Quantitative Reasoning', 'Geometry / Perimeter'),
    ('Quantitative Reasoning', 'Geometry / Volume'),
    ('Quantitative Reasoning', 'Geometry / Volume / Cubes'),
    ('Quantitative Reasoning', 'Geometry / Volume / Rectangular prisms'),
    ('Quantitative Reasoning', 'Geometry / Circumference'),
    ('Quantitative Reasoning', 'Time Calculations'),
    ('Quantitative Reasoning', 'Time Calculations / Timetables'),
    ('Quantitative Reasoning', 'Time Calculations / Scheduling'),
    ('Quantitative Reasoning', 'Time Calculations / Duration'),
    ('Quantitative Reasoning', 'Time Calculations / Time zones'),
    ('Quantitative Reasoning', 'Multi-Step Calculations'),
    ('Situational Judgement', 'Patient welfare and safety'),
    ('Situational Judgement', 'Patient welfare and safety / Patient safety'),
    ('Situational Judgement', 'Patient welfare and safety / Infection risk'),
    ('Situational Judgement', 'Patient welfare and safety / Scope of competence'),
    ('Situational Judgement', 'Patient welfare and safety / Escalating concerns'),
    ('Situational Judgement', 'Professional conduct'),
    ('Situational Judgement', 'Professional conduct / Professionalism'),
    ('Situational Judgement', 'Professional conduct / Honesty and accountability'),
    ('Situational Judgement', 'Professional conduct / Confidentiality'),
    ('Situational Judgement', 'Professional conduct / Respect and dignity'),
    ('Situational Judgement', 'Professional conduct / Following protocol'),
    ('Situational Judgement', 'Teamwork and communication'),
    ('Situational Judgement', 'Teamwork and communication / Speaking up'),
    ('Situational Judgement', 'Teamwork and communication / Peer concern'),
    ('Situational Judgement', 'Teamwork and communication / Conflict with colleague'),
    ('Situational Judgement', 'Teamwork and communication / Seeking senior support'),
    ('Situational Judgement', 'Teamwork and communication / Patient interaction'),
    ('Situational Judgement', 'Personal judgement'),
    ('Situational Judgement', 'Personal judgement / Workload and prioritisation'),
    ('Situational Judgement', 'Personal judgement / Wellbeing and mental health'),
    ('Situational Judgement', 'Personal judgement / Managing commitments'),
    ('Situational Judgement', 'Personal judgement / Career opportunity vs responsibility'),
    ('Situational Judgement', 'Personal judgement / Peer pressure'),
    ('Situational Judgement', 'Ethical principles'),
    ('Situational Judgement', 'Ethical principles / Beneficence'),
    ('Situational Judgement', 'Ethical principles / Non-maleficence'),
    ('Situational Judgement', 'Ethical principles / Autonomy'),
    ('Situational Judgement', 'Ethical principles / Justice'),
    ('Situational Judgement', 'Ethical principles / Consent'),
    ('Situational Judgement', 'Ethical principles / Confidentiality')
)
UPDATE public.question_tags tag
SET
  description = public.__tmp_ucat_taxonomy_description_doc(
    CASE
      WHEN tag_paths.parent_question_tag_id IS NULL
        THEN 'Use this tag family for questions where ' || lower(tag_paths.name) || ' is the main skill being practiced. Review it by asking what method or judgement the question required.'
      ELSE 'Use this tag when ' || lower(tag_paths.name) || ' is the specific skill that made the question difficult. Review it by identifying the clue, rule, or calculation step that mattered.'
    END
  ),
  updated_at = NOW()
FROM tag_paths
LEFT JOIN described_paths
  ON described_paths.section_name = tag_paths.section_name
  AND described_paths.path = tag_paths.path
WHERE tag.id = tag_paths.id
  AND described_paths.path IS NULL;

DROP FUNCTION public.__tmp_ucat_taxonomy_description_doc(TEXT);
