name: Admin Web Build

on:
  push:
    branches: [main]
    paths:
      - 'apps/admin-web/**'
      - 'packages/**'
      - 'turbo.json'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-turbo-
      - run: npm ci
      - run: npx turbo run build --filter=altitutor-admin-app
      # TODO: Add deploy step (e.g., Vercel, Docker push, etc.)

