name: Supabase Deploy

on:
  push:
    branches: [develop, main]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/functions/**'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: supabase-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Select project (branch → project)
        id: project
        run: |
          if [ "${{ github.ref_name }}" = "develop" ]; then
            echo "project=${{ secrets.SUPABASE_DEV_PROJECT_ID }}" >> $GITHUB_OUTPUT
          else
            echo "project=${{ secrets.SUPABASE_PROD_PROJECT_ID }}" >> $GITHUB_OUTPUT
          fi

      - name: Export CLI env (PROJECT_ID, DB_PASSWORD)
        run: |
          echo "SUPABASE_PROJECT_ID=${{ steps.project.outputs.project }}" >> $GITHUB_ENV
          if [ "${{ github.ref_name }}" = "develop" ]; then
            echo "SUPABASE_DB_PASSWORD=${{ secrets.SUPABASE_DEV_DB_PASSWORD }}" >> $GITHUB_ENV
          else
            echo "SUPABASE_DB_PASSWORD=${{ secrets.SUPABASE_PROD_DB_PASSWORD }}" >> $GITHUB_ENV
          fi

      - name: Link project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Push migrations
        run: supabase db push

      - name: Lint remote schema (post-push)
        run: supabase db lint --linked --level error --fail-on error

      - name: Generate TypeScript types (shared package)
        run: |
          mkdir -p packages/shared/src/supabase
          supabase gen types typescript --project-id $SUPABASE_PROJECT_ID --schema public > packages/shared/src/supabase/generated.ts

      - name: Commit updated types (if changed)
        run: |
          if [ -n "$(git status --porcelain packages/shared/src/supabase/generated.ts)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add packages/shared/src/supabase/generated.ts
            git commit -m "chore: update Supabase types [skip ci]"
            git push
          else
            echo "No type changes to commit"
          fi

      - name: Deploy edge functions (if any)
        if: ${{ contains(github.event.head_commit.message, '[skip-functions]') == false }}
        run: |
          if [ -d "supabase/functions" ]; then
            for fn in $(ls supabase/functions); do
              supabase functions deploy --no-verify-jwt "$fn" --project-ref $SUPABASE_PROJECT_ID || true
            done
          fi





