name: Update DB Types

on:
  push:
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  update-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Generate types (dev)
        run: SUPABASE_PROJECT_ID=${{ secrets.SUPABASE_DEV_PROJECT_ID }} npm run db:types:remote
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      - name: Commit changes (if any)
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add apps/admin-web/src/shared/lib/supabase/database/generated.ts
          git diff --quiet --cached || git commit -m "chore: update DB types [skip ci]"
      - name: Push
        run: git push

